### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by Gliscor** [iamkroot/trakt-scrobbler#10]
OS: Windows 7 Home Premium x64
Python Version: 3.7.3 x64 (checked "add to system path" when installing)
Player: MPC-HC (Nightly, 64-bit) 1.8.6.8 (bf1f52f12)
 
When i run `scripts\windows-install.bat` i get this screen, `pipenv` is already installed as you can see...
![image](https://user-images.githubusercontent.com/11700855/59867215-973a5400-935b-11e9-840c-a6cfc97971bd.png)

**Comment by iamkroot** [comment]
Try typing just `pipenv` in the cmd prompt. Is that working?

**Comment by Gliscor** [comment]
> Try typing just `pipenv` in the cmd prompt. Is that working?

Yes
![image](https://user-images.githubusercontent.com/11700855/59966807-7145b880-94ef-11e9-9208-9d7865ed19ea.png)

**Comment by iamkroot** [comment]
Hmm, and what does `where pipenv` give as output?

**Comment by GiacomoLaw** [comment]
That warning doesn't have anything to do with pipenv, or with this tool. It's just saying your pip version is outdated. Pipenv has been installed fine and the tool will work.

**Comment by iamkroot** [comment]
> That warning doesn't have anything to do with pipenv, or with this tool. It's just saying your pip version is outdated. Pipenv has been installed fine and the tool will work.
> 
> [datatofish.com/upgrade-pip](https://datatofish.com/upgrade-pip/)

That warning is probably irrelevant to this issue. Seems like an issue with the `where` command, just waiting for @Gliscor to confirm.

**Comment by Gliscor** [comment]
> where pipenv

Got this:
![image](https://user-images.githubusercontent.com/11700855/60074684-7d996380-96f1-11e9-93ac-ed4282b91dec.png)

**Comment by Gliscor** [comment]
> That warning doesn't have anything to do with pipenv, or with this tool. It's just saying your pip version is outdated. Pipenv has been installed fine and the tool will work.
> 
> https://datatofish.com/upgrade-pip/

This isn't about the warning, see the second line on my 1st screenshot, it says "Please install pipenv first", it ask me to install pipenv but it is already installed

**Comment by GiacomoLaw** [comment]
My bad. Have your tried running the script after installing pipenv? Looks like it's installed successfully to me.

**Comment by Gliscor** [comment]
> My bad. Have your tried running the script after installing pipenv? Looks like it's installed successfully to me.

of course, just looks like it doesn't detect `pipenv`
![image](https://user-images.githubusercontent.com/11700855/60075599-acb0d480-96f3-11e9-9940-9b8b5b6ff7ef.png)

**Comment by GiacomoLaw** [comment]
Odd - not sure what is causing that, sorry!

**Comment by iamkroot** [comment]
@Gliscor Just a shot in the dark, but try in a non administrator command prompt?

**Comment by Gliscor** [comment]
> @Gliscor Just a shot in the dark, but try in a non administrator command prompt?

I get same output:
![image](https://user-images.githubusercontent.com/11700855/60738610-f0de7900-9f2c-11e9-8543-57d29d4866a5.png)

**Comment by iamkroot** [comment]
I've made some updates to the windows install script. Could you try now please?

**Comment by Gliscor** [comment]
> I've made some updates to the windows install script. Could you try now please?

Hi, I tried again, looks like it has something to do with the PATH thingy:
![image](https://user-images.githubusercontent.com/11700855/61240638-b4223700-a70f-11e9-8b2d-b26e2302cee7.png)
Here's how my PATH's look like:
User variables:
![image](https://user-images.githubusercontent.com/11700855/61240692-d025d880-a70f-11e9-98a8-664214885544.png)
User PATH:
![image](https://user-images.githubusercontent.com/11700855/61240722-df0c8b00-a70f-11e9-8594-9577e7392554.png)
System variables:
![image](https://user-images.githubusercontent.com/11700855/61240763-f5b2e200-a70f-11e9-8496-3a98f4cb7554.png)
and System PATH:
![image](https://user-images.githubusercontent.com/11700855/61240786-06635800-a710-11e9-875b-1141563e713a.png)

**Comment by iamkroot** [comment]
Try `where pipenv || echo Y u no work`

**Comment by iamkroot** [comment]
I've made some more updates to the installation script. Try now?

**Comment by Gliscor** [comment]
> I've made some more updates to the installation script. Try now?

Hi, I tried today and no luck:
![image](https://user-images.githubusercontent.com/11700855/61887892-7de37500-aed0-11e9-8e53-07d492eb47ca.png)

**Comment by iamkroot** [comment]
In the prompt, run `pipenv --version >NUL 2>&1 || echo Unable to run pipenv.`.

Separately, open notepad, paste the above command and save it as `test-pipenv.bat` in some folder. Then open cmd in that folder and run `.\test-pipenv.bat`. Let's see if both are working or not.

**Comment by achessoux** [comment]
Both work: no answer.
If I run pipenv --version I tête 11.9.0

Le ven. 26 juil. 2019 à 08:27, Krut Patel <notifications@github.com> a
écrit :

**Comment by Gliscor** [comment]
> In the prompt, run `pipenv --version >NUL 2>&1 || echo Unable to run pipenv.`.
> 
> Separately, open notepad, paste the above command and save it as `test-pipenv.bat` in some folder. Then open cmd in that folder and run `.\test-pipenv.bat`. Let's see if both are working or not.

First test:
![image](https://user-images.githubusercontent.com/11700855/61985674-4364ff80-afd8-11e9-8a7d-13fbb4a38347.png)
Second test:
![image](https://user-images.githubusercontent.com/11700855/61985755-9c349800-afd8-11e9-8b35-b5838bc08135.png)

**Comment by iamkroot** [comment]
@Gliscor does only `pipenv --version` give any errors?

**Comment by Gliscor** [comment]
> @Gliscor does only `pipenv --version` give any errors?
> 
![image](https://user-images.githubusercontent.com/11700855/62326827-089e1400-b47d-11e9-8aee-713dd4add987.png)

> Also, try `pipenv --version || echo No pipenv`

![image](https://user-images.githubusercontent.com/11700855/62326858-181d5d00-b47d-11e9-99e2-3c41329fd9c5.png)

**Comment by iamkroot** [comment]
Hmm we're getting close to the problem.
Try `pipenv --version 1>NUL || echo No pipenv` and `pipenv --version 2>&1 || echo No pipenv` and again, `pipenv --version 1>NUL 2>&1 || echo No pipenv`

**Comment by Gliscor** [comment]
> Hmm we're getting close to the problem.
> Try `pipenv --version 1>NUL || echo No pipenv` 
![image](https://user-images.githubusercontent.com/11700855/62368522-d03d1b00-b4fa-11e9-96f1-21c74dfc8f7a.png)
and `pipenv --version 2>&1 || echo No pipenv`
![image](https://user-images.githubusercontent.com/11700855/62368547-f06cda00-b4fa-11e9-8bf1-f9461b29d631.png)
 
and again, `pipenv --version 1>NUL 2>&1 || echo No pipenv`
![image](https://user-images.githubusercontent.com/11700855/62368577-01b5e680-b4fb-11e9-90ca-a0c9dc24d79a.png)

**Comment by iamkroot** [comment]
Aha there it is. Looks like a problem with your `NUL` piping, possibly because of a bug in the old-ish OS. I suggest removing `>NUL` in all the places where it occurs in `scripts/windows-install.bat`. It's just used for suppressing unnecessary output, won't affect the installation.

**Comment by iamkroot** [comment]
The error is tracked in pallets/click#1065.

**Comment by Gliscor** [comment]
> Aha there it is. Looks like a problem with your `NUL` piping, possibly because of a bug in the old-ish OS. I suggest removing `>NUL` in all the places where it occurs in `scripts/windows-install.bat`. It's just used for suppressing unnecessary output, won't affect the installation.

like this?
[1.txt](https://github.com/iamkroot/trakt-scrobbler/files/3469360/1.txt)

**Comment by iamkroot** [comment]
Yup that should work. Save it as a `.bat` and execute.

**Comment by Gliscor** [comment]
Well... it didn't went very well, here we go:

![image_2019-08-06_13-42-03](https://user-images.githubusercontent.com/11700855/62565887-c77b7a80-b855-11e9-80fd-6c924fd6b5a4.png)
when it starts "creating the virtual environment" the memory usage stars to increase, lots of python.exe processes (400+) appears in the task manager:
![image_2019-08-06_13-48-42](https://user-images.githubusercontent.com/11700855/62566090-2c36d500-b856-11e9-918c-f52c3293bcdc.png)
 and after 5 ~ 7 minutes the pc starts to get really slow and a windows pop up sayin the pc is running low on memory:
![image_2019-08-06_13-49-20](https://user-images.githubusercontent.com/11700855/62566167-55576580-b856-11e9-8a4c-319bb5920456.png)
when i click "ok" all the python.exe process start to disappear one by one and the memory usage returns to normal:
![image_2019-08-06_13-58-04](https://user-images.githubusercontent.com/11700855/62566269-9a7b9780-b856-11e9-9a63-55fb2d880229.png)
![image_2019-08-06_13-58-33](https://user-images.githubusercontent.com/11700855/62566300-a6675980-b856-11e9-8685-cd3a429d2daa.png)
![image_2019-08-06_13-58-49](https://user-images.githubusercontent.com/11700855/62566321-b5e6a280-b856-11e9-98c6-80ba59ed6e2e.png)
![image_2019-08-06_13-59-36](https://user-images.githubusercontent.com/11700855/62566352-c26afb00-b856-11e9-9b27-975d323689fc.png)
the last 3 pics are part of the final output, i couldn't get it dumped all to a txt using `>>`, this is what was recorded in the `output.txt` file: 
[output.txt](https://github.com/iamkroot/trakt-scrobbler/files/3473670/output.txt)

**Comment by iamkroot** [comment]
Ok there is definitely something wrong with your system. It's not able to run `xcopy` and `where` commands, which are supposed to be available by default since Windows XP SP3.

Try typing just `xcopy` in a prompt and see if it can be found.

**Comment by Gliscor** [comment]
> Ok there is definitely something wrong with your system. It's not able to run `xcopy` and `where` commands, which are supposed to be available by default since Windows XP SP3.
> 
> Try typing just `xcopy` in a prompt and see if it can be found.

![image](https://user-images.githubusercontent.com/11700855/62643403-e7727300-b915-11e9-839f-c6c26908e473.png)
running as admin:
![image](https://user-images.githubusercontent.com/11700855/62643465-03761480-b916-11e9-9471-50149dda073c.png)

**Comment by iamkroot** [comment]
Maybe your `PATH` variable doesn't have `C:\Windows\System32`. Try adding it once and see if it runs in a non admin prompt.

**Comment by Gliscor** [comment]
> Maybe your `PATH` variable doesn't have `C:\Windows\System32`. Try adding it once and see if it runs in a non admin prompt.

Hi, i did it but nothing changed:
![image](https://user-images.githubusercontent.com/11700855/63111065-de5b5480-bf5a-11e9-9f44-1c41b13c7236.png)
I get the same output:
![image](https://user-images.githubusercontent.com/11700855/63111112-fdf27d00-bf5a-11e9-8c47-5f7cd8a41768.png)

**Comment by iamkroot** [comment]
@Gliscor You have to add `C:\Windows\System32` to your `PATH` variable, which already exists. So, int the system variables section, there will be a `PATH` variable, edit it, and add this folder to it. You don't have to make a `System32` as a separate variable.

**Comment by Gliscor** [comment]
I think i'll just format my PC and try again, thanks.
