### ISSUE TITLE
Handle media titles containing years in Plex

### ISSUE THREAD

**Issue by iamkroot** [iamkroot/trakt-scrobbler#100]
For other media players, we use [guessit](https://github.com/guessit-io/guessit/) on the file path, and since it uses regexes under the hood, it picks up the year if present in the name. Using that, the scrobbler actually does specify the year when doing a trakt search. But for Plex, the year is a part of the media title, and we're not doing anything fancy to detect/extract years.

_Originally posted by @iamkroot in https://github.com/iamkroot/trakt-scrobbler/issues/95#issuecomment-749592561_

> The Hardy Boys, on plex it's named as The Hardy Boys (2020) but doing a search on trakt as that does not provide a search result, instead you'd have to search it as just The Hardy Boys on trakt to get a result. Doing so though provides results for all the other The Hardy Boys tv shows as well which would probably result in the same issue with Mulan. Not all TV Shows have this issue, as for example the 2016 tv show of MacGyver you can search for both MacGyver (2016) (which is the way that it appears on plex) and MacGyver and get the result that you need (though the later provides the results of the other MacGyver tv shows and movies as well. (this just happened so I have a fresh log if needed)

_Originally posted by @JourneyOver in https://github.com/iamkroot/trakt-scrobbler/issues/95#issuecomment-749409329_

**Comment by JourneyOver** [comment]
So far this has been working for the issue with the hardy boys and I'm sure others that have the year in the title as well that may have had this issue (hardy boys was the first one and only one so far out of several shows that have years in them that I have that I ran into this issue with).

Not sure if it'll fix the other issue I mentioned in #95 as well or not where it'll pick up the wrong trakt ID for a show / movie, as the Mulan movie has so far been the first and only one I've ran into so far that has had that issue.

**Comment by iamkroot** [comment]
As long as there haven't been two Mulan movies in the same year, this should fix the issue. The monitor now uses the year field from Plex metadata, if available (which is almost always true), to limit the results from the trakt search. The feature request from #95 is still valid, mostly for other media players which don't store any metadata about the media library, and we have to guess everything from only the file path.
