### ISSUE TITLE
[Feature Request] Support for iina

### ISSUE THREAD

**Issue by raghav4** [iamkroot/trakt-scrobbler#102]
[iina](https://iina.io) is a quite popular media player for Mac. Please consider having support for it too!

**Comment by iamkroot** [comment]
From the github repo, it looks like IINA uses libmpv at its core, and it seems to have a way to allow the user to specify mpv options via the CLI or config. If this is the case, the default steps for [mpv setup](https://github.com/iamkroot/trakt-scrobbler/wiki/Players-Setup#mpv) should work for you too, with a slight modification. If you choose to use the CLI option, it will look something like `iina [file] --mpv-input-ipc-server=/tmp/mpvsocket` (note the extra `mpv` in option name). The config file option should work as specified in the wiki page.

Don't forget to add mpv to your monitored players list: `trakts config set --add players.monitored mpv`. Do report back on how it goes.

**Comment by iamkroot** [comment]
There doesn't seem to be anything special required from our side to add iina support. The MPV monitor ought to work well enough.
