### ISSUE TITLE
Update Trakt with skips

### ISSUE THREAD

**Issue by GiacomoLaw** [iamkroot/trakt-scrobbler#11]
Hi there

I usually skip intros - was wondering if it was possible to ping Trakt to keep the time stamp up to date?

Thanks!

**Comment by iamkroot** [comment]
It does do that already :) I've set the threshold to 10% of total duration as the minimum jump it should consider as a skip, and update trakt. I'll get this added to the config soon, but if you want, you can manually set it from [line 59 in monitor.py](https://github.com/iamkroot/trakt-scrobbler/blob/8350480dac9bff018360d18f47343c74ef55845f/trakt_scrobbler/player_monitors/monitor.py#L59) in your install location, and reboot afterwards.

**Comment by GiacomoLaw** [comment]
Awesome, thanks!
