### ISSUE TITLE
support for http links

### ISSUE THREAD

**Issue by Alistair1231** [iamkroot/trakt-scrobbler#114]
**Describe the bug**

A clear and concise description of what the bug/error is.

**Desktop (please complete the following information):**
 - OS and Version: Windows 10
 - Python Version: 3.7.9
 - Player and Version: mpv 0.33.0

**To Reproduce**

1. Open a file with a link i.e. http://server/folder/file.mp4

Basically I think the issue is that I cannot whitelist the ip/server since it is an URL. Is there a way for using an empty blacklist or something?
I just want it to scrobble anything opened in mpv.

EDIT: https://github.com/stareInTheAir/mpv-trakt-sync-daemon works fine, so I moght just use that

**Comment by iamkroot** [comment]
Yeah, I recently added code to _ignore_ http links in mpv: https://github.com/iamkroot/trakt-scrobbler/commit/2dd86ed2e2634fb1796911ca28bd8fbfe94d050d The reason is simple, there were some false positives when playing files from youtube due to the current assumption that everything is based on absolute local paths.
Thanks for pointing out https://github.com/stareInTheAir/mpv-trakt-sync-daemon, it seems guessit is able to handle URLs fairly well. I've been meaning to explore this, so you can expect an update sometime soon.

**Comment by Alistair1231** [comment]
> 
> 
> Yeah, I recently added code to _ignore_ http links in mpv: [2dd86ed](https://github.com/iamkroot/trakt-scrobbler/commit/2dd86ed2e2634fb1796911ca28bd8fbfe94d050d) The reason is simple, there were some false positives when playing files from youtube due to the current assumption that everything is based on absolute local paths.
> Thanks for pointing out https://github.com/stareInTheAir/mpv-trakt-sync-daemon, it seems guessit is able to handle URLs fairly well. I've been meaning to explore this, so you can expect an update sometime soon.
> 
> PS: Until then, you could try using [`httpfs`](https://github.com/Kurocon/HTTPfs) to mount the web server as a local path, and then our scrobbler should be able to handle it properly.

Sorry for the late reply. Yes I actually am doing that with rclone for plex, which I am running locally. However when watching together with friends, sometimes Plex's Watch together feature doesn't quite work as expected and for those cases we use [Syncplay](https://syncplay.pl/) together with MPV. Syncplay has a shared playlist function which allows me to just add HTTP links and both of us have easy access to it. Otherwise everyone would have to create a mount with rclone which is a hassle.
Also, [https://github.com/stareInTheAir/mpv-trakt-sync-daemon](https://github.com/stareInTheAir/mpv-trakt-sync-daemon) actually refuses to work with Syncplay. It only works when opening MPV manually for whatever reason.

**Comment by iamkroot** [comment]
> Also, [stareInTheAir/mpv-trakt-sync-daemon](https://github.com/stareInTheAir/mpv-trakt-sync-daemon) actually refuses to work with Syncplay. It only works when opening MPV manually for whatever reason.

I'm afraid you'll have the same issue with syncplay, since we use the same mechanism for monitoring MPV (IPC server) and it seems that syncplay randomizes the ipc-path every time it runs. We'd have to find a reliable way to get this path:
1. Syncplay doesn't seem to respect the `--input-ipc-server` argument specified by the user. If support for this is added, we won't require any changes to the scrobbler. 
2. Somehow figure out the ipc path, feels extremely hacky and brittle.

**Comment by iamkroot** [comment]
Hey @Alistair1231 I've added basic support for this, could you please test it out and let me know if I missed anything?

To install, stop the scrobbler, then run `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git@mpv-http`.
You will also need to add the server to your whitelist, and I haven't yet updated the `trakts whitelist` command to support links. So for now, I recommend using the config command directly: `trakts config set --add fileinfo.whitelist "https://example.com/"`. 

Do report back on how it works, I haven't tested it very thoroughly on Windows.

**Comment by Alistair1231** [comment]
Hey. Thanks!
I still am encountering issues though. However maybe I updated incorrectly?
This is the powershell log:
![image](https://user-images.githubusercontent.com/26165288/119240248-b39a2900-bb4e-11eb-9911-3a59f0ea55d2.png)
This is part of the log file
![image](https://user-images.githubusercontent.com/26165288/119240294-eb08d580-bb4e-11eb-9b16-fb6a45d5b844.png)

The errors you can see came from restarting mpv, before a file was played so shouldn't worried about I think.

Also worth mentioning, that I started mpv like this:
```mpv --input-ipc-server=\\.\mpvsocket```
This is because when I was previously debugging this whole mpv http trakt business (not sure if this script or the other I linked) I noticed when looking at all the pipes in windows that the pipe actually used by mpv was ```\\.\pipe\pipe\mpvsocket``` and that was why I had issues.
And without the ```\pipe``` it seems to work...
I don't know any specifics however...

**Comment by Alistair1231** [comment]
close was accident

**Comment by iamkroot** [comment]
Hmm I'm pretty sure this is because of an incorrect update. The latest version shouldn't be creating the `File is not local` log at all. 
Try reinstalling it properly. `pipx uninstall trakt-scrobbler`, followed by `pipx install git+https://github.com/iamkroot/trakt-scrobbler.git@mpv-http`.

**Comment by Alistair1231** [comment]
I figured as much. After reinstalling properly:
![image](https://user-images.githubusercontent.com/26165288/119346561-a9854100-bc9a-11eb-8f44-e02d80e94471.png)


Here is what happened when I started mpv like this ```mpv --input-ipc-server=\\.\mpvsocket``` and opened a link like this: ```https://user:pass@adress.com/files/_Plex/TV/show/season/file.mkv```
![image](https://user-images.githubusercontent.com/26165288/119346770-f0733680-bc9a-11eb-91d8-afffc50e02a6.png)


then I restarted trakts
![image](https://user-images.githubusercontent.com/26165288/119347248-8d35d400-bc9b-11eb-8030-f9b14b2bfd8b.png)


and ran an url in syncplay
![image](https://user-images.githubusercontent.com/26165288/119347267-958e0f00-bc9b-11eb-9d70-05411f1296f3.png)

**Comment by iamkroot** [comment]
That what happens when I write code without testing :3 I made a refactor, but didn't test the windows code-paths. I've fixed it, and an update should handle it on your side too. This time, the force update _should_ work: `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git@mpv-http`

**Comment by Alistair1231** [comment]
I tested it with and without syncplay and it works! Thanks! 
One thing which is of note and maybe worth changing,
If I whitelist ```https://user:pass@example.com/``` it works, but if I leave out the user and pass in the url then it doesn't. 
Since there normally cannot be @ or : signs in urls (afaik), maybe the user and password stuff could just be ignored when checking if the url is whitelisted?
But that's a minor thing.

Thanks for your time!

**Comment by iamkroot** [comment]
Glad to see it's working!

Regarding the Auth thing, it is called the userinfo section, and it actually a part of the URL definition according to the [standard](https://tools.ietf.org/html/rfc3986#section-3.2.1). I'm using a library to match urls (to support wildcards), and it does support the userinfo section explicitly so no need to make any changes, current behaviour is expected and correct.

**Comment by Alistair1231** [comment]
Alright then. So will this be merged on master? So that the next version includes these changes?

**Comment by iamkroot** [comment]
Yes, that's the case. I'm still waiting on a feature from the urlmatch library that would enhance perf. (https://github.com/jessepollak/urlmatch/issues/8) Once that's available, I'll merge this into master and release the next version.

**Comment by Alistair1231** [comment]
Great thanks again for your work and for sharing it as FOSS! :)
