### ISSUE TITLE
Add option to disable pause/resume notifications

### ISSUE THREAD

**Issue by iamkroot** [iamkroot/trakt-scrobbler#117]
This is a bit non-trivial to implement. This is because there's no such thing as "resume" scrobble. Only start, pause and stop are valid. So I'll have to add more code to track the last scrobble and detect if it's a start or a resume in `scrobbler.py`. 

_Originally posted by @iamkroot in https://github.com/iamkroot/trakt-scrobbler/issues/115#issuecomment-821990316_

**Comment by visua0** [comment]
I understand start vs resume is difficult to detect. I would personally already be happy with just the ability to disable individual notification types so I could leave stop and maybe pause notifications enabled (and definitely error ones if those get added).
The resume ones are annoying to me since they pop up on top of the video I'm trying to watch, and I tend to pause frequently.
A start-not-resume notification would definitely be nice to have as an option though.

**Comment by iamkroot** [comment]
Done! Please try this out when you get time. Install using: `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git@notif-categories`

To enable/disable a specific category, use the config command: `trakts config set general.enable_notifs.scrobble.resume no`
To see all the available categories, see https://github.com/iamkroot/trakt-scrobbler/blob/1935f9825e8a7598dda23dc99496ded6d521aa3b/trakt_scrobbler/config_default.yaml

You can even blanket-ban categories: `trakts config set general.enable_notifs.scrobble no` will disable all scrobble notifications, and `trakts config set general.enable_notifs no` will simply do what it says.

**Comment by visua0** [comment]
Sounds perfect. Unfortunately I'm running into an exception:
```
2021-05-09 14:10:19,779 - INFO - scrobbler - scrobbler - Scrobble start successful for [...]
2021-05-09 14:10:19,779 - ERROR - scrobbler - __init__ - Unhandled exception
Traceback (most recent call last):
  File "trakt_scrobbler\__init__.py", line 42, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "trakt_scrobbler\scrobbler.py", line 21, in run
    self.scrobble(*scrobble_item)
  File "trakt_scrobbler\scrobbler.py", line 43, in scrobble
    self.notify(msg, category=f"scrobble.{category}")
  File "trakt_scrobbler\notifier.py", line 113, in notify
    toaster.show_toast(title, body, duration=timeout, threaded=True)
NameError: name 'toaster' is not defined
2021-05-09 14:10:19,781 - ERROR - scrobbler - __init__ - Exception while notifying user.
Traceback (most recent call last):
  File "trakt_scrobbler\__init__.py", line 42, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "trakt_scrobbler\scrobbler.py", line 21, in run
    self.scrobble(*scrobble_item)
  File "trakt_scrobbler\scrobbler.py", line 43, in scrobble
    self.notify(msg, category=f"scrobble.{category}")
  File "trakt_scrobbler\notifier.py", line 113, in notify
    toaster.show_toast(title, body, duration=timeout, threaded=True)
NameError: name 'toaster' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trakt_scrobbler\__init__.py", line 21, in error_logger
    Notifier().notify(f"Check log file.\n{exc_info[1]}", "Unhandled Exception",
  File "trakt_scrobbler\notifier.py", line 113, in notify
    toaster.show_toast(title, body, duration=timeout, threaded=True)
NameError: name 'toaster' is not defined
```

**Comment by visua0** [comment]
Easy fix: `toaster` should be `self.toaster`

**Comment by iamkroot** [comment]
> Easy fix: on line 113 `toaster` should be `self.toaster`

Yep, I'd missed changing that during the refactor. I've pushed the fix to the branch. You don't need to update since you've already manually fixed it. 


> Seems to be working perfectly now.

Awesome!


>  I'll let you know if I run into any issues with it.

Try playing around (aka try to break) the `trakts config set general.enable_notifs...` command. That's the one I'm most doubtful about, since it's pretty brittle. Would be happy to know if I missed anything.
