### ISSUE TITLE
MPV - Just can't seem to get this to work (Windows)

### ISSUE THREAD

**Issue by aynatiq8** [iamkroot/trakt-scrobbler#119]
**Describe the bug**

I've been at this for days trying to at least get scrobbling to work for trakt, but I just can't. I've tried everything I could find and I'm at a point where I have to ask for help. I don't know what the bug is since this might be like the 3rd or fourth time i've opened command prompt in my life, but I'll try my best in reproducing what I did underneath.

**Desktop (please complete the following information):**
 - OS and Version: Windows 10
 - Python Version: 3.9.4
 - Player and Version: MPV v2.0.0.0

**To Reproduce**

1. Followed everything in the installation guide, don't know if it was successful or not since I did not get a code to enter into trakt after I selected the players I wanted to monitor, mpv was '2'
2. Then went to monitor MPV and did everything it asked, (the .conf file stuff), but with that I still did not get any notifications or anything when opening MPV for scrobbling
3. Closed player (watched the entire episode), still nothing, and nothing in trakt (the website)
4. I then went looking for ways to make this work, and came across the mpv-trakt-sync-daemon
5. Still couldn't get MPV to work (scrobble) after i followed everything such as installing guessit for example (don't know if that did anything or not as well)
6. I reached the end of the steps, and thought this was going to work because I did not come across something that stopped me from moving on to the next step, untill I got a bad magic number in 'trakt_key_holder'
7. I couldn't find a solution that worked - delete all the .pyc files (did manually for like two hours) since find . -name '*.pyc' -delete (or any of the other commands suggested) are all - File not found - '*.pyc' - so that didn't work and I kept getting an error that 'trakt_key_holder' is missing but I followed the 'solution' and deleted all the .pyc files considering it was one too. Then I returned the 'trakt_key_holder' to it's original location from trash and got the bad magic number error again. I still didn't think I'd be able to get it to work even if I did not get that error anyways since things hadn't been going too smooth
8. I then gave up, and am now here
9. See error in log file - don't know if this is the complete thing, meaning everything I've done (doesn't seem like it), but I'm sure someone will help me along the way If i did something wrong regarding this

**Log file**
[trakt_scrobbler.log](https://github.com/iamkroot/trakt-scrobbler/files/6369457/trakt_scrobbler.log)

Please notify me of any personal information I may have missed in the log file. I deleted most of the personal stuff that I know of and could find here. Again, don't really know what I'm doing. I just want to scrobble my shows, and hope this gets as good as Taiga is with anime in the future (don't know if that's possible or not with trakt since I don't really understand all this stuff)

For the log contents under here, again I don't know how to get this to work since Idk anything about coding and inputting stuff into command prompt but I did try everything my brain could think of for ways around this. Sorry and bear with me please. I'm willing to delete everything I have installed and try again with someone along the way. I'll be here and will try my best to reply as soon as possible, so just wanted to let whoever's willing to help to not worry about late replies.

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
(replace this line) *PASTE LOG FILE CONTENTS HERE* Command: "trakts log open" or "trakts log path"
```
</p>
</details>

**Comment by aynatiq8** [comment]
Oh and I forgot to mention that in the log file, there is MPC-HC (if mpv did not work thats why i selected it) and plex related stuff in there since I wanted to be able to scrobble for all three (with mpv ofc), but then decided mpv will just do the job, and keep it simple.

**Comment by iamkroot** [comment]
You seem to have removed too much info from the log file. Particularly, there should be some lines around 
```
2021-04-23 00:03:33,972 - DEBUG - MainThread - monitor - Failed to autoload value from 'C:\Users\Abdulrahman Alaynati\AppData\Roaming\mpv\mpv.conf'
2021-04-23 00:03:33,979 - ERROR - MainThread - monitor - Config value autoload failed for mpv.
```

These lines contain the error info, and will give a proper insight into why the config value autoload failed. Please paste those here.

**Comment by iamkroot** [comment]
Also, are you sure you are using the correct MPV - https://mpv.io ? That is the one this scrobbler supports, and its latest version is 0.33.0, whereas you have written v2.0.0 for some reason in your original bug report.

**Comment by aynatiq8** [comment]
Will this do?

2021-04-23 00:03:32,845 - DEBUG - MainThread - utils - C:\Users\Abdulrahman Alaynati\AppData\Roaming\trakt-scrobbler\watched_backlog.json doesn't exist.
2021-04-23 00:03:33,508 - INFO - MainThread - scrobbler - Started scrobbler thread.
2021-04-23 00:03:33,972 - DEBUG - MainThread - monitor - Failed to autoload value from 'C:\Users\Abdulrahman Alaynati\AppData\Roaming\mpv\mpv.conf'
2021-04-23 00:03:33,979 - ERROR - MainThread - monitor - Config value autoload failed for mpv.
2021-04-23 00:03:33,982 - WARNING - MainThread - main - Could not start monitor for mpv
2021-04-23 00:03:33,984 - DEBUG - MainThread - monitor - Failed to autoload value from 'Software\MPC-HC\MPC-HC\Settings'
2021-04-23 00:03:33,990 - ERROR - MainThread - monitor - Config value autoload failed for mpc-hc.
2021-04-23 00:03:33,991 - WARNING - MainThread - main - Could not start monitor for mpc-hc

**Comment by iamkroot** [comment]
Umm, aren't there more lines in between these?

**Comment by aynatiq8** [comment]
How do I figure out what version my MPV is?

![image](https://user-images.githubusercontent.com/83099509/115957825-4f635580-a50d-11eb-8aad-8049b4c6014c.png)
I honestly just went with this

**Comment by aynatiq8** [comment]
> Umm, aren't there more lines in between these?

That's all there was there, but maybe there's some other way?

**Comment by iamkroot** [comment]
>  I honestly just went with this

Looking at the other files, it does seem to be the correct MPV. To verify, you can "Shift+Right Click" on that folder, and it will give "Open Powershell here" (or something like that). Open that, then run `.\mpv.exe --version`.

**Comment by iamkroot** [comment]
> That's all there was there, but maybe there's some other way?

Hmm then in that case, the most likely reason is that your conf file is not present. Where did you put `mpv.conf` after editing it?

**Comment by aynatiq8** [comment]
![image](https://user-images.githubusercontent.com/83099509/115957999-1f688200-a50e-11eb-9939-7d5d56954883.png)

**Comment by iamkroot** [comment]
Wat. Does something come up when you just run `.\mpv.exe`?

**Comment by aynatiq8** [comment]
![image](https://user-images.githubusercontent.com/83099509/115958045-5e96d300-a50e-11eb-911d-49cccea87328.png)

**Comment by aynatiq8** [comment]
> Wat. Does something come up when you just run `.\mpv.exe`?

![image](https://user-images.githubusercontent.com/83099509/115958073-7bcba180-a50e-11eb-9303-a0028c943320.png)
 
It Just opens up the player when i do that

**Comment by iamkroot** [comment]
Your conf file is wrong. The first line, `/tmp/mpvsocket` is for linux. Delete that line.

**Comment by aynatiq8** [comment]
> Your conf file is wrong. The first line, `/tmp/mpvsocket` is for linux. Delete that line.

What should I replace it with?

**Comment by iamkroot** [comment]
Just delete it. The second line is all that is required.

**Comment by iamkroot** [comment]
that should work. Restart the scrobbler with `trakts start --restart` in the powershell window you have open

**Comment by aynatiq8** [comment]
> Just delete it. The second line is all that is required.

**Comment by aynatiq8** [comment]
Oops idk what i did there, but yeah here it is 

![image](https://user-images.githubusercontent.com/83099509/115958191-0c09e680-a50f-11eb-9367-b487e741edc9.png)

**Comment by iamkroot** [comment]
just run `trakts status` again. If that still shows "not running", paste the log file again (after removing passwords, obviously)

**Comment by aynatiq8** [comment]
> just run `trakts status` again. If that still shows "not running", paste the log file again (after removing passwords, obviously)

It's now running I believe

![image](https://user-images.githubusercontent.com/83099509/115958253-5be8ad80-a50f-11eb-8775-44d6efb259d3.png)

**Comment by iamkroot** [comment]
Try playing some file, and check the log file just in case (it should show "Started monitor for mpv")

**Comment by aynatiq8** [comment]
God why can't I find the log file, is there a command I can input?

**Comment by iamkroot** [comment]
`trakts log open` is your friend

**Comment by aynatiq8** [comment]
![image](https://user-images.githubusercontent.com/83099509/115958450-445df480-a510-11eb-90ee-3719a15cfbfa.png)

It doesn't look like it started monitoring mpv

**Comment by iamkroot** [comment]
Hmm I'm stumped. Let's try something else.
1. `trakts config set players.mpv.ipc_path \\.\pipe\mpv` 
2. Restart with `trakts start -r`
3. `.\mpv` and then drag and drop some file.
4. Check log to see if scrobble started (wait 10 secs)

**Comment by aynatiq8** [comment]
> Hmm I'm stumped. Let's try something else.
> 
> 1. `trakts config set players.mpv.ipc_path \\.\pipe\mpv`
> 2. Restart with `trakts start -r`
> 3. Start mpv and then drag and drop some file.
> 4. Check log to see if scrobble started (wait 10 secs)

![image](https://user-images.githubusercontent.com/83099509/115958838-e205f380-a511-11eb-90ef-77e8dbc167cf.png)

**Comment by iamkroot** [comment]
Did you try playing something through mpv?

**Comment by aynatiq8** [comment]
> Hmm I'm stumped. Let's try something else.
> 
> 1. `trakts config set players.mpv.ipc_path \\.\pipe\mpv`
> 2. Restart with `trakts start -r`
> 3. Start mpv and then drag and drop some file.
> 4. Check log to see if scrobble started (wait 10 secs)

![image](https://user-images.githubusercontent.com/83099509/115958927-3e691300-a512-11eb-9017-06cc21b2530e.png)

Sorry I forgot to remove something important :) 
Here it is again

**Comment by aynatiq8** [comment]
> Did you try playing something through mpv?

Yeah

![image](https://user-images.githubusercontent.com/83099509/115958963-63f61c80-a512-11eb-95dc-89e043fae890.png)

**Comment by aynatiq8** [comment]
Oh wait should i be playing a TV SHOW? I'll just do that as well one second

**Comment by iamkroot** [comment]
> Yeah

In that case I can mostly guess it's a problem with your `mpv.conf` since MPV isn't starting the connection.


> Oh wait should i be playing a TV SHOW? I'll just do that as well one second

Not really, it would have worked with any file - something should have come up in the log file, but it didn't.

**Comment by aynatiq8** [comment]
> > Yeah
> 
> In that case I can mostly guess it's a problem with your `mpv.conf` since MPV isn't starting the connection.
> 
> > Oh wait should i be playing a TV SHOW? I'll just do that as well one second
> 
> Not really, it would have worked with any file - something should have come up in the log file, but it didn't.

Is there a way around the mpv.conf file? I thought u mentioned we only need - ut-ipc-server=\\.\pipe\mpv

**Comment by iamkroot** [comment]
`mpv --input-ipc-server=\\.\pipe\mpv` try running this and then drag your file to play

**Comment by aynatiq8** [comment]
![image](https://user-images.githubusercontent.com/83099509/115959267-0e227400-a514-11eb-8c4d-209429669d9b.png)

It doesn't look like it updated anything, the last time was - **2021-04-24 15:24:33,742** - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path. Now its 3:46

**Comment by iamkroot** [comment]
no no that's wrong. `mpv --input-ipc-server=\\.\pipe\mpv` should go in your powershell window, not your conf file.

**Comment by aynatiq8** [comment]
![image](https://user-images.githubusercontent.com/83099509/115959469-044d4080-a515-11eb-80cb-64b005fce9ac.png)

**Comment by iamkroot** [comment]
Ah damn you Windows! First run `cmd` inside the powershell window and then run the same command i sent above. that should start your mpv window. Also, close the existing mpv window.

**Comment by aynatiq8** [comment]
![image](https://user-images.githubusercontent.com/83099509/115959679-11b6fa80-a516-11eb-8866-1e4566dd85ee.png)

that did something, looks like we're getting somewhere :)

**Comment by aynatiq8** [comment]
now i drag and drop a file into mpv and look at the log file?

**Comment by aynatiq8** [comment]
> Ah damn you Windows! First run `cmd` inside the powershell window and then run the same command i sent above. that should start your mpv window. Also, close the existing mpv window.

Oh and that command didn't start MPV

**Comment by iamkroot** [comment]
Woah wait a minute. You're using mpv v0.28.0. That is wayyyy too old (it says 2017 right there). It didn't support IPC server back then, which we use to communicate with the scrobbler. You will first have to install an updated version of MPV (v0.33.0 seems to be the latest) from https://mpv.io

**Comment by iamkroot** [comment]
I have a feeling installing the latest version should fix everything.

**Comment by aynatiq8** [comment]
> I have a feeling installing the latest version should fix everything.

oh man i really hope so

**Comment by aynatiq8** [comment]
> Woah wait a minute. You're using mpv v0.28.0. That is wayyyy too old (it says 2017 right there). It didn't support IPC server back then, which we use to communicate with the scrobbler. You will first have to install an updated version of MPV (v0.33.0 seems to be the latest) from https://mpv.io

will do then

**Comment by iamkroot** [comment]
https://sourceforge.net/projects/mpv-player-windows/files/64bit/ use this link

**Comment by iamkroot** [comment]
https://sourceforge.net/projects/mpv-player-windows/files/latest/download use this link

**Comment by aynatiq8** [comment]
Sorry it took me a while t get back to you, but yeah I'm following the instructions rn, and this is what i have

![image](https://user-images.githubusercontent.com/83099509/115962220-ef77a980-a522-11eb-8a00-e94b06c46f08.png)

Should i do something about the force thing? and do u recommend i use powershell or cmd for doing this?

**Comment by aynatiq8** [comment]
I went on and did everything since u sadly weren't there. Made a new .conf file since I deleted/uninstalled the previous old MPV, pasted what u told me to keep, and I still keep getting this.

2021-04-24 20:40:07,561 - INFO - MainThread - scrobbler - Started scrobbler thread.
2021-04-24 20:40:07,608 - INFO - MainThread - monitor - Started monitor for mpv
2021-04-24 20:40:07,623 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path.

I opened MPV yesterday. played something for more than a minute, and this is what I got after running trakts log open^^

![image](https://user-images.githubusercontent.com/83099509/115990536-67e67500-a5cc-11eb-9864-31256e3d7f4f.png)

This is the new .conf file I made

![image](https://user-images.githubusercontent.com/83099509/115990552-8187bc80-a5cc-11eb-8d81-c60fe35e7b27.png)

And this is the new location for mpv, and the .conf file

**Comment by aynatiq8** [comment]
> I went on and did everything since u sadly weren't there. Made a new .conf file since I deleted/uninstalled the previous old MPV, pasted what u told me to keep, and I still keep getting this.
> 
> 2021-04-24 20:40:07,561 - INFO - MainThread - scrobbler - Started scrobbler thread.
> 2021-04-24 20:40:07,608 - INFO - MainThread - monitor - Started monitor for mpv
> 2021-04-24 20:40:07,623 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path.
> 
> I opened MPV yesterday. played something for more than a minute, and this is what I got after running trakts log open^^
> 
> ![image](https://user-images.githubusercontent.com/83099509/115990536-67e67500-a5cc-11eb-9864-31256e3d7f4f.png)
> 
> This is the new .conf file I made
> 
> ![image](https://user-images.githubusercontent.com/83099509/115990552-8187bc80-a5cc-11eb-8d81-c60fe35e7b27.png)
> 
> And this is the new location for mpv, and the .conf file

Forgot to mention that I opened MPV as well just now, dragged and dropped a file to start playing, waited more than a minute, and ran `trakts log open` but I didn't even get the error I got yesterday, which means it isn't updating for some cases and I dont know why that's happening.

2021-04-24 20:40:07,623 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path.

**Comment by iamkroot** [comment]
Hmm I'm out of ideas at this point. It's important to note that mpv is a bit difficult to configure for novices. For now, I suggest just using some other player (like MPCBE or VLC) and setting up the scrobbler with it.
