### ISSUE TITLE
Problem with user name separated by space?

### ISSUE THREAD

**Issue by porkslapchop** [iamkroot/trakt-scrobbler#12]
Desktop
 - OS: Windows 10
 - Player MPC-HC Fork
 - Player Version 1.8.6

**To Reproduce**
- Create a user account and name it " NameA NameB" separated by a space
- Start the windows install batch file

**Logs**
Setup complete. Starting device authentication.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'trakt_interface'
'C:\Users\Mohamed' is not recognized as an internal or external command,
operable program or batch file.
Done.

**Comment by iamkroot** [comment]
Should be fixed with the latest commit ^_^
