### ISSUE TITLE
[enhancement] Jellyfin Support

### ISSUE THREAD

**Issue by JourneyOver** [iamkroot/trakt-scrobbler#122]
Been thinking about moving to jellyfin lately, they do already have a trakt plugin but it doesn't seem to work very well (or at least I've been having issues with it) and your trakt scrobbler hasn't let me down yet on plex side of things, so was hoping that there could possibly be some support added for jellyfin.

homepage: https://jellyfin.org/
source: https://github.com/jellyfin/jellyfin
API information: https://api.jellyfin.org/

**Comment by iamkroot** [comment]
>  do already have a trakt plugin but it doesn't seem to work very well

In that case, shouldn't it be better to report issues to them and have them fix it? I would certainly prefer avoiding redundant work. And their [plugin](https://github.com/jellyfin/jellyfin-plugin-trakt) development does seem to be semi-active at least.

**Comment by JourneyOver** [comment]
egh just forget it, honestly don't wanna put in the effort to even move over and deal with having to change up so much stuff..
