### ISSUE TITLE
Provide alternative to entering plex user/password during init

### ISSUE THREAD

**Issue by JRFarmer** [iamkroot/trakt-scrobbler#131]
During `trakts init` the user is asked for plex username and password in order to fetch the authentication token.

I don't give my password to anybody. So I stopped for a minute to study the trakt-scrobbler code, and I read https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/. Then I fetched my token and manually created ~/.local/share/trakt-scrobbler/plex_token.json.

Perhaps give the user a way to just provide the token during init?

**Comment by iamkroot** [comment]
This feels a bit over the top. Consider-
1. The password is never stored in the computer. We just make a call to plex and store the token immediately.
2. Expecting a normal user to even _choose_ between password/token during init seems unnecessary.
3. If you can manage to find the token yourself, you could also store it manually (to `plex_token.json`) and after that, it is just a matter of rerunning `trakts init`.

**Comment by iamkroot** [comment]
I've added a `--token` option to the `trakts plex` command that can be used to enter the token directly. (Currently, there is no check for correctness of token). However, this commnd _must_ be run before init. The default flow still remains username+password.
