### ISSUE TITLE
What happens when offline ?

### ISSUE THREAD

**Issue by Seluj78** [iamkroot/trakt-scrobbler#132]
Hi there, love the tool, I've just started using it but I love it !

I got a question, what happens when I'm watching a movie without an internet connections ? Nothing ? Are the logs pushed when a connection is restored ?

Thanks !

**Comment by JRFarmer** [comment]
There is a backlog that will scrobble when back online.
https://github.com/iamkroot/trakt-scrobbler/wiki/How-It-Works#backlog-cleaner

**Comment by Seluj78** [comment]
Amazing ! That's all I wanted to know ! Thanks for all the great work
