### ISSUE TITLE
Updatable notifications on Linux are broken

### ISSUE THREAD

**Issue by iamkroot** [iamkroot/trakt-scrobbler#133]
A recent update to KDE Plasma (v5.22) has broken the behaviour of `replaces_id` in the notification daemon. See https://bugs.kde.org/show_bug.cgi?id=440051

We need to add more bookkeeping to track whether the previous notification has closed, since we can only use the replaces_id for a live notification. This will need adding a DBUS signal handler to the notifier, and will really complicate state management. It seems to be more trouble than it is worth, better to kill this feature completely.

I believe, after the addition of fast_pause to the mpv monitor, we don't really generate that many notifications in a short duration.

**Comment by iamkroot** [comment]
@ahmubashshir what do you think?

**Comment by ahmubashshir** [comment]
I'll try using NotficiationClosed to unset replaces_id :3

**Comment by iamkroot** [comment]
@ahmubashshir I really don't recommend that. The current notifier module is a "fire-and-forget" model, and I do not want to complicate it by having signal handlers over there. Updatable notifications are not worth all the extra effort.

**Comment by ahmubashshir** [comment]
ok...
	Mubashshir

**Comment by ahmubashshir** [comment]
then we can just ignore notification id :3
	Mubashshir
