### ISSUE TITLE
[BUG] Unable to setup on headless server

### ISSUE THREAD

**Issue by Generator** [iamkroot/trakt-scrobbler#136]
## Description
Trying to setup on a headless Plex server ```trakts init``` tries to open browser and ends in error.

```
trakts init
This will guide you through the setup of the scrobbler.                             
If you wish to quit at any point, press Ctrl+C or Cmd+C                             
Select the players that should be monitored (separate using comma):                 
 [0] mpc-be
 [1] mpc-hc
 [2] mpv
 [3] plex
 [4] vlc
 > 3
Selected: plex
Plex token is saved.
Remember to configure your player(s) as outlined at https://github.com/iamkroot/trakt
-scrobbler/wiki/Players-Setup
Failed to authorize application with Trakt. Run 'trakts auth' manually to retry.    

[KeyError]
'DBUS_SESSION_BUS_ADDRESS'
```
```

trakts auth
Open https://trakt.tv/activate in your browser and enter this code: ********

[KeyError]
'DBUS_SESSION_BUS_ADDRESS'
```

**Desktop (please complete the following information):**
 - OS and Version: Debian Buster
 - Python Version: Python 3.7.3
 - Player and Version: Plex Media Server 1.23.6.4881

**To Reproduce**

1. Setup Plex Media Server on headless or docker.
2. Run trakt-scrobbler (```trakts init``` or ```trakts auth```) from headless or docker container.

**Comment by iamkroot** [comment]
This is most likely happening when the app tries to send a notification - this requires dbus, which is probably missing on the container
Run `trakts config set general.enable_notifs no` before running the init command. This will disable notifications completely.

**Comment by Generator** [comment]
That why when trying to auth with trakt prints trakt page on terminal

![ksnip_20210806-154930](https://user-images.githubusercontent.com/44146/128529123-3b50e809-0996-456d-9193-17d0e041bad7.png)

**Comment by iamkroot** [comment]
> Open the webpage on w3m (terminal web browser). Was able to continue setup after closing the browser.

Yeah, we just blindly use Python's [`webbrowser`](https://docs.python.org/3/library/webbrowser.html) module to open up the website, and this falls back to text mode browsers like links and w3m, which is why you saw that in your terminal.
I guess it is better to exclude those browsers from being opened.

**Comment by iamkroot** [comment]
Hey @Generator, I've added some fixes for the above two issues. If you have a few minutes, could you please retry running init? This will help the next person who finds themself if the same situation as you:
1. Stop the scrobbler with `trakts stop`
2. Run `trakts config set general.enable_notifs yes` to re-enable the notifs (you can/should turn it off later)
3. Run `mv ~/.local/share/trakt-scrobbler/trakt_token.json ~/.local/share/trakt-scrobbler/trakt_token.json.bak` to clear the trakt token
4. Run `pipx install --force --pip-args='--force-reinstall' git+https://github.com/iamkroot/trakt-scrobbler.git@headless`
5. Start init with `trakts init`

Let me know if you face the same issues again (notifs, w3m).

**Comment by Generator** [comment]
Did a clean ```trakts init``` (renamed trakt-scrobbler directories), was able to run init without issues.

**Comment by iamkroot** [comment]
Awesome! Thanks for creating the bug report and the follow-up discussion :)
