### ISSUE TITLE
[Installation] Import Error DLL Load failed with Python 3.8

### ISSUE THREAD

**Issue by s1kee** [iamkroot/trakt-scrobbler#144]
Import error when running 'trakts init' help?

![image](https://user-images.githubusercontent.com/89289139/130310570-2c65572c-3ce0-420f-aa4f-378233a6be54.png)

**Comment by iamkroot** [comment]
What are your windows and python versions?

**Comment by s1kee** [comment]
win 10, python 3.8.5

**Comment by iamkroot** [comment]
Were there any errors during `pipx install`?

**Comment by s1kee** [comment]
no i dont think so

**Comment by iamkroot** [comment]
1. What is the output of `pipx runpip trakt-scrobbler freeze`? 
2. Try `pipx reinstall trakt-scrobbler` and retry init

**Comment by s1kee** [comment]
appdirs==1.4.4
babelfish==0.6.0
certifi==2021.5.30
charset-normalizer==2.0.4
cleo==0.8.1
clikit==0.6.2
confuse==1.5.0
crashtest==0.3.1
guessit==3.3.1
idna==3.2
pastel==0.2.1
pylev==1.4.0
pypiwin32==223
python-dateutil==2.8.2
pywin32==301
PyYAML==5.4.1
rebulk==3.0.1
requests==2.26.0
six==1.16.0
trakt-scrobbler==1.3.0
urllib3==1.26.6
urlmatch==1.0.1
win10toast==0.9

**Comment by s1kee** [comment]
reinstalled it, got the same error :(

**Comment by iamkroot** [comment]
Hmm that's weird indeed :/

Looks like this error isn't new-
https://github.com/mhammond/pywin32/issues/1431 
https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api

Let's try this:
1. Open up powershell/cmd as admin (Win+X, admin console)
2. `cd "C:\Users\<your username>\.local\pipx\venvs\trakt-scrobbler\Scripts\`
3. `python pywin32_postinstall.py -install`

**Comment by s1kee** [comment]
![image](https://user-images.githubusercontent.com/89289139/130394345-94e8dfb0-726e-4cab-ae57-258f5797385f.png)

says dll load failed :( looks like i rlly wont be able to use this hahaha thanks for the help though really appreciate it!

**Comment by iamkroot** [comment]
I think I missed a step in the previous instructions: as a step 2.5, run `.\activate.bat` and then run step 3.

If that doesn't work either, you could try one last thing- simply use python 3.7 instead of python 3.8. 
1. Uninstall the existing app `pipx uninstall trakt-scrobbler`
2. Install python3.7 from https://www.python.org/downloads/release/python-379/
	* Note the installation folder here: It will be something like `C:\Username\AppData\Local\Programs\Python\Python37\`
3. Install app `pipx install --python="C:\Username\AppData\Local\Programs\Python\Python37\python.exe" trakt-scrobbler`

**Comment by s1kee** [comment]
helloo, sorry for the vv late reply ive been busy but came back here and tried it and it works now!! thank you so muchh

**Comment by iamkroot** [comment]
That's great, but what exactly worked? The previous method, or installing python 3.7? Would be helpful for someone else facing the same issue.

**Comment by s1kee** [comment]
Installing python 3.7 :)

**Comment by iamkroot** [comment]
Ah that's a shame. Would've preferred to get python 3.8 working, as I was thinking of deprecating 3.7. But good to see that the issue is resolved.
