### ISSUE TITLE
[BUG] ImportError: cannot import name 'Notifier' from 'trakt_scrobbler.notifier'

### ISSUE THREAD

**Issue by listy-bit** [iamkroot/trakt-scrobbler#149]
**Describe the bug**

When trying to set any notifier setting, ImportError arises.

**Desktop (please complete the following information):**
 - OS and Version: [Mac 10.11]
 - Python Version: [3.9]
 - Trakts 1.3.1

`
trakts config set general.enable_notifs.exception true

  ImportError

  cannot import name 'Notifier' from 'trakt_scrobbler.notifier' (/Users/XXXXXXXX/.local/pipx/venvs/trakt-scrobbler/lib/python3.9/site-packages/trakt_scrobbler/notifier.py)

  at .local/pipx/venvs/trakt-scrobbler/lib/python3.9/site-packages/trakt_scrobbler/commands/config.py:64 in handle_enable_notifs
       60│ 
       61│     def handle_enable_notifs(self, config, view, key, values):
       62│         if len(values) != 1:
       63│             raise ValueError("Given parameter only accepts a single value")
    →  64│         from trakt_scrobbler.notifier import Notifier
       65│ 
       66│         value = values[0].lower() in self.TRUTHY_BOOL
       67│ 
       68│         view = view["general"]["enable_notifs"]
`

**Comment by iamkroot** [comment]
Thanks a lot for the bug report! I'd missed some parts when refactoring. Fixed now. You can install it using these steps:
1. Stop the scrobbler with `trakts stop`
2. Run `pipx install --force --pip-args='--force-reinstall' git+https://github.com/iamkroot/trakt-scrobbler.git`
3. Start scrobbler with `trakts start`
