### ISSUE TITLE
Percentage needed for the script to update the media to trakt

### ISSUE THREAD

**Issue by hxpelessrxmantic301** [iamkroot/trakt-scrobbler#158]
Since the discussion link is not working for me, i decided to post this matter here because i dont know what else to do...so like it says in the title, whats the minimum watch time needed for it to start updating to trakt..there is this app called taiga.moe ...its used only for anime but there is a feature where we can adjust the watch time needed for it to update that we have watched that episode...so is there such a feature in this script? if not, whats the default?

**Comment by iamkroot** [comment]
> the minimum watch time needed for it to start updating to trakt

There's a difference between MAL/AniList/etc. and Trakt that you seem to be overlooking. MAL only cares about when you finished watching that episode, whereas Trakt is more detailed-
* As soon as you start playing the ep (close to 0%), this app sends a "Playing now" scrobble to Trakt, which shows up on your dashboard on the site.
* When you do a pause/stop at any point, it will immediately get sent to Trakt.
* So you should note that the app will always send updates to trakt (every time you play/pause/stop), no matter your progress. This is much more precise than MAL.

Now there's the question of what progress counts as "Completed" on Trakt. 
[Trakt docs](https://trakt.docs.apiary.io/reference/scrobble/stop) state that if you "stop" the file before **80%** progress, it will count as a pause- meaning that you intend to resume watching it as some later point, and it won't be marked as "Completed" on Trakt right now.
This app also follows the same convention.

**Comment by hxpelessrxmantic301** [comment]
> > the minimum watch time needed for it to start updating to trakt
> 
> There's a difference between MAL/AniList/etc. and Trakt that you seem to be overlooking. MAL only cares about when you finished watching that episode, whereas Trakt is more detailed-
> 
>     * As soon as you start playing the ep (close to 0%), this app sends a "Playing now" scrobble to Trakt, which shows up on your dashboard on the site.
> 
>     * When you do a pause/stop at any point, it will immediately get sent to Trakt.
> 
>     * So you should note that the app will always send updates to trakt (every time you play/pause/stop), no matter your progress. This is much more precise than MAL.
> 
> 
> Now there's the question of what progress counts as "Completed" on Trakt. [Trakt docs](https://trakt.docs.apiary.io/reference/scrobble/stop) state that if you "stop" the file before **80%** progress, it will count as a pause- meaning that you intend to resume watching it as some later point, and it won't be marked as "Completed" on Trakt right now. This app also follows the same convention.

Okay, I understand now. Thanks!
