### ISSUE TITLE
[BUG] trakt-scrobbler can't find mpv.conf of a portable mpv installation.

### ISSUE THREAD

**Issue by sbstratos79** [iamkroot/trakt-scrobbler#159]
**Describe the bug**

The scrobbler can't find mpv.conf of a portable mpv installation. This would've been fine if there were a config option to change the mpv.conf lookup directory. But I couldn't find any such option.

**Desktop (please complete the following information):**
 - Windows 11
 - Python 3.9.7
 - mpv 0.34.0-16-gec16769c2d

**To Reproduce**

1. Use a portable_config instead of storing config in "...\AppData\Roaming\mpv\"
2.  I get ![this error](https://user-images.githubusercontent.com/4395586/141641200-e7182254-e226-4d13-8c5e-79bac3cbb947.png)

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
2021-11-13 16:21:49,711 - INFO - MainThread - scrobbler - Started scrobbler thread.
2021-11-13 16:21:49,726 - DEBUG - MainThread - monitor - Failed to autoload value from 'C:\\Users\\sbstr\\AppData\\Roaming\\mpv\\mpv.conf': File not found
2021-11-13 16:21:49,726 - ERROR - MainThread - monitor - Config value autoload failed for mpv.
2021-11-13 16:21:49,726 - WARNING - MainThread - main - Could not start monitor for mpv
```
</p>
</details>

**Comment by iamkroot** [comment]
Yeah, the auto-detection from config is only a convenience feature to make the setup simpler for most users, and only checks the default config location.
In your case, it will be simpler to just specify the `ipc-path` manually via `trakts config players.mpv.ipc_path <ipc_path>`. See the [`MPV Wrappers`](https://github.com/iamkroot/trakt-scrobbler/wiki/Players-Setup#wrappers) section in wiki for more info.

**Comment by sbstratos79** [comment]
Thanks. It's working now. You forgot to add `set` between `trakts config` but I verified it from the link you provided. Just mentioned it in case someone else comes across this issue and finds this thread.

**Comment by sbstratos79** [comment]
> What was the ipc_path that you used @sbstratos79?

In mpv.conf I added 
`input-ipc-server=\\.pipe\mpvsocket`
That's the IPC socket i used for trakts config as well.

**Comment by the-nos4a2** [comment]
2022-05-19 17:22:00,233 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path.
I get this error.

**Comment by the-nos4a2** [comment]
Do I need to do anything else to make it work?

**Comment by sbstratos79** [comment]
> Do I need to do anything else to make it work?

Did you run `trakts config set players.mpv.ipc_path \\.\pipe\mpvsocket` after adding ipc path in mpv.conf?

**Comment by the-nos4a2** [comment]
Yes

![image](https://user-images.githubusercontent.com/66081804/169376927-af71ed0c-189b-459a-a4ed-8db5293ac3cc.png)

**Comment by the-nos4a2** [comment]
Do mpv need to be open?

**Comment by sbstratos79** [comment]
> Do mpv need to be open?

Specifying the IPC socket in mpv.conf and trakts config and restarting trakts did the trick for me. I have no idea why it's not working for you

**Comment by the-nos4a2** [comment]
Maybe I need to have a whitelist

**Comment by iamkroot** [comment]
@the-nos4a2 Are you sure MPV is reading the correct config? You can try enabling debug logs for mpv to verify that the `input-ipc-server` is indeed `\\.\pipe\mpvsocket`

**Comment by iamkroot** [comment]
> 2022-05-19 17:22:00,233 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path. I get this error.

Do you get this error even when MPV is running?

**Comment by sbstratos79** [comment]
> @the-nos4a2 Whitelist doesn't have anything to do with it. 
> 
> Are you sure MPV is reading the correct config?
> 1. You can try enabling debug logs for mpv (`mpv.exe --msg-level=debug`) to verify that the `input-ipc-server` is indeed `\\.\pipe\mpvsocket`.
> 2. You can also test if mpv is reachable by entering `echo show-text ${playback-time} >\\.\pipe\mpvsocket` in a command prompt/powershell when MPV is running. (It will show the playback time in the MPV GUI)
> 
> If this doesn't show anything, something is wrong with your MPV config. See [FILES](https://mpv.io/manual/stable/#files) section in the MPV manual.

I didn't really need to do this since trakts scrobbler is working for me but just out of curiosity, I tried running `mpv --msg-level=debug`
And I got this error:
```
Expected '=' and a value.
Error parsing option msg-level (option parameter could not be parsed)
Setting commandline option --msg-level=debug failed.
Exiting... (Fatal error)
```

**Comment by iamkroot** [comment]
Ah, my mistake. Looks like the correct syntax is `--msg-level=all=debug` (we need to specify the modules for which the level should be set).

Thanks for the catch!

**Comment by the-nos4a2** [comment]
> > 2022-05-19 17:22:00,233 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path. I get this error.
> 
> Do you get this error even when MPV is running?

Yes

**Comment by iamkroot** [comment]
@the-nos4a2 I suggest creating a new issue and filling out its template.
