### ISSUE TITLE
plex-mpv-shim support

### ISSUE THREAD

**Issue by ronilaukkarinen** [iamkroot/trakt-scrobbler#163]
I'm looking for a real time trakt scrobble support for [plex-mpv-shim](https://github.com/iwalton3/plex-mpv-shim). It seems trakts doesn't currently recognize it.

**Comment by ronilaukkarinen** [comment]
Never mind, [PlexTraktSync](https://github.com/Taxel/PlexTraktSync) seems to work so moving on to it.

**Comment by iamkroot** [comment]
Did you enable the Plex monitor, or the mpv monitor for this?
This scrobbler won't be able to recognize the custom mpv that is used by that app, but the plex monitor should work well enough.
