### ISSUE TITLE
[BUG] Unable to load config.toml!

### ISSUE THREAD

**Issue by bramdsgn** [iamkroot/trakt-scrobbler#17]
**Describe the bug**
I followed the instructions [https://www.thenerdystudent.com/2019/06/trakt-scrobbler/](here)
I got the same error over and over.

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64]
 - Player VLC
 - Player Version [3.0.7.1]

PS H:\trakt-scrobbler> scripts\windows-install.bat
Installing to "C:\Users\bram\AppData\Local\trakt-scrobbler"
Installing dependencies from Pipfile.lock (b0e854)…
Ignoring dbus-python: markers 'sys_platform != "win32"' don't match your environment
Ignoring notify2: markers 'sys_platform != "win32"' don't match your environment
  ================================ 16/16 - 00:00:13
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Adding to startup commands.
Setup complete. Starting device authentication.
Unable to load config.toml!
Done.

what's the problem? 
and how do I start over? (because it worked at once before)

**Comment by iamkroot** [comment]
Are you creating the `config.toml` file before running the script?

**Comment by iamkroot** [comment]
I've updated the windows install script. Could you please try again from scratch?

**Comment by bramdsgn** [comment]
> Are you creating the `config.toml` file before running the script?

yes

**Comment by bramdsgn** [comment]
> I've updated the windows install script. Could you please try again from scratch?

will do, thanks

**Comment by bramdsgn** [comment]
I delete the folder in \appdata 
re downloaded the zip
created the config.toml first (changed the port to 4212, because Lua Telnet in vlc is set to 4212)

and I got the same thing:

PS H:\trakt-scrobbler> scripts\windows-install.bat
Installing to "C:\Users\bram\AppData\Local\trakt-scrobbler"
Installing dependencies from Pipfile.lock (b0e854)…
Ignoring dbus-python: markers 'sys_platform != "win32"' don't match your environment
Ignoring notify2: markers 'sys_platform != "win32"' don't match your environment
  ================================ 16/16 - 00:00:16
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Adding to startup commands.
Setup complete. Starting device authentication.
Unable to load config.toml!
Done.

**Comment by iamkroot** [comment]
Seems this is happening mostly because your toml file is invalid. Try putting it through [here](http://toml-online-parser.ovonick.com) first to catch any errors.

**Comment by bramdsgn** [comment]
> Seems this is happening mostly because your toml file is invalid. Try putting it through [here](http://toml-online-parser.ovonick.com) first to catch any errors.

yeah apparently there is a problem in the way the path to folders is written

**[fileinfo] 
whitelist = [
	"D:\Videos\Movies"
	"D:\Videos\TV"
]**

_Was expecting escape after '\', but got 'V'
Line number: 6 Column: 6 Line: 	"D:\Videos\Movies"_


I don't get it, how else am I gonna write it?

**Comment by bramdsgn** [comment]
> > Seems this is happening mostly because your toml file is invalid. Try putting it through [here](http://toml-online-parser.ovonick.com) first to catch any errors.
> 
> yeah apparently there is a problem in the way the path to folders is written
> 
> **[fileinfo] whitelist = [ "D:\Videos\Movies" "D:\Videos\TV" ]**
> 
> _Was expecting escape after '', but got 'V' Line number: 6 Column: 6 Line: "D:\Videos\Movies"_
> 
> I don't get it, how else am I gonna write it?

I just tried removing it all together and I got this !!!

**PS H:\trakt-scrobbler> scripts\windows-install.bat
Installing to "C:\Users\bram\AppData\Local\trakt-scrobbler"
Installing dependencies from Pipfile.lock (b0e854)…
Ignoring dbus-python: markers 'sys_platform != "win32"' don't match your environment
Ignoring notify2: markers 'sys_platform != "win32"' don't match your environment
  ================================ 16/16 - 00:00:20
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Adding to startup commands.
Setup complete. Starting device authentication.
data\trakt_cache.json doesn't exist.
data\trakt_token.json doesn't exist.
Done.
PS H:\trakt-scrobbler>**

I even did a verification (PIN on trakt) but don't think it worked

**Comment by iamkroot** [comment]
> I don't get it, how else am I gonna write it?
You aren't allowed to use backslashes (`\`) inside double quotes. Sample config contains single quotes wherever windows paths (with `\` as separators) are used.

I suppose this should be made clearer in the docs. Everything else worked btw.

**Comment by iamkroot** [comment]
Also, are you sure you're running the latest version? The `data\trakt_cache.json doesn't exist.` line shouldn't appear now.

**Comment by bramdsgn** [comment]
> Also, are you sure you're running the latest version? The `data\trakt_cache.json doesn't exist.` line shouldn't appear now.

yeah man, you can check, I was surprised to see that the data folder was gone!

**Comment by bramdsgn** [comment]
> > I don't get it, how else am I gonna write it?
> 
> You aren't allowed to use backslashes (`\`) inside double quotes. Sample config contains single quotes wherever windows paths (with `\` as separators) are used.
> 
> I suppose this should be made clearer in the docs. Everything else worked btw.

thank you for the clarification, the toml file is fixed now. but still "Unable to load" error (used the old zip)

**Comment by iamkroot** [comment]
Delete everything from `%APPDATA%\trakt-scrobbler` and `%LOCALAPPDATA\trakt-scrobbler`, then run the install script from the latest zip. Some of the old files might be remaining.

**Comment by bramdsgn** [comment]
now I think everything is set, thank you!

still not syncing though. I think it's the port 

[players.vlc]  # enable web interface from options
ip = "localhost"
port = "4212"
password = "password"
poll_interval = 10

8080 is used by qbittorent, and in VLC Lua Telnet is set to 4212. so I was wondering if Lua Telnet port = 4212 is what I should be looking at?

**Comment by iamkroot** [comment]
Try opening `localhost:4212` in your web browser with vlc running and check if its accessible.

**Comment by bramdsgn** [comment]
> Try opening `localhost:4212` in your web browser with vlc running and check if its accessible.

all is set now! I think!
I just need to find a way to make it detect files like this "Tom.Clancy's.Jack.Ryan.S01E03.Black.22.720p.WEBRip.2CH.x265.HEVC-PSA.mkv" 😅 

I appreciate the help, thank you ;)

**Comment by iamkroot** [comment]
> I just need to find a way to make it detect files like this "Tom.Clancy's.Jack.Ryan.S01E03.Black.22.720p.WEBRip.2CH.x265.HEVC-PSA.mkv" 

That works already. The default media info module is able to handle that easily, and gives the correct output. (`MatchesDict([('title', "Tom Clancy's Jack Ryan"), ('season', 1), ('episode', 3), ('episode_title', 'Black 22'), ('screen_size', '720p'), ('source', 'Web'), ('other', 'Rip'), ('audio_channels', '2.0'), ('video_codec', 'H.265'), ('video_profile', 'High Efficiency Video Coding'), ('release_group', 'PSA'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])`)

If you aren't seeing the scrobbles, the problem is somewhere else.

**Comment by iamkroot** [comment]
> 8080 is used by qbittorent, and in VLC Lua Telnet is set to 4212. so I was wondering if Lua Telnet port = 4212 is what I should be looking at?

Seems like you need to edit `Preferences -> All -> Input/codecs -> HTTP Server Port`.

**Comment by bramdsgn** [comment]
> > 8080 is used by qbittorent, and in VLC Lua Telnet is set to 4212. so I was wondering if Lua Telnet port = 4212 is what I should be looking at?
> 
> Seems like you need to edit `Preferences -> All -> Input/codecs -> HTTP Server Port`.

Yeah I think everything is set, 
I mean "localhost:8080" CAN be open

**Comment by bramdsgn** [comment]
> > I just need to find a way to make it detect files like this "Tom.Clancy's.Jack.Ryan.S01E03.Black.22.720p.WEBRip.2CH.x265.HEVC-PSA.mkv"
> 
> That works already. The default media info module is able to handle that easily, and gives the correct output. (`MatchesDict([('title', "Tom Clancy's Jack Ryan"), ('season', 1), ('episode', 3), ('episode_title', 'Black 22'), ('screen_size', '720p'), ('source', 'Web'), ('other', 'Rip'), ('audio_channels', '2.0'), ('video_codec', 'H.265'), ('video_profile', 'High Efficiency Video Coding'), ('release_group', 'PSA'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])`)
> 
> If you aren't seeing the scrobbles, the problem is somewhere else.

well in that case I really don't know where the problem is.
I appreciate you trying to help.

cheers,
