### ISSUE TITLE
[BUG] plex: 401 Client Error

### ISSUE THREAD

**Issue by listy-bit** [iamkroot/trakt-scrobbler#170]
Trakts fails to scrobble any Plex video, reporting a 401 permission error with Plex.

**Desktop (please complete the following information):**
 - OS and Version: Mac 10.10
 - Python Version: 3.8.5
 - Player and Version: Plex 1.22.2.4282-a97b03fad
 - Trakts 1.3.2

**To Reproduce**

1. Play any item in any player
4. See error in log file

$trakts auth gives result: Token valid until 01/05/22
$trakts plex gives result: Plex token is saved.

**To Resolve**
$trakts init

I have no idea why plex would suddenly reject trakts.
Shouldn't $trakts plex delete the stored token and start authorisation again? For me it seems to just confirm that there is a token, without checking it's valid.

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```
2021-12-24 23:32:30,185 - ERROR - plex - monitor - Error while getting data from plex: 401 Client Error: Unauthorized for url: http://localhost:32400/status/sessions
2021-12-24 23:32:30,212 - WARNING - plex - monitor - plex monitor stopped
```
</p>
</details>

**Comment by iamkroot** [comment]
It does seem like an auth error. But `trakts plex` will not try to override your token, and there's no `trakts plex delete`. You need to run `trakts plex --force` in order to clear the token and redo it.

**Comment by wmazoni** [comment]
I am also accepting the same error on windows. It is as if the password entered is not being accepted in the terminal.

**Comment by iamkroot** [comment]
@wmazoni try `trakts plex --force` again? And make sure the plex server url is correct

**Comment by wmazoni** [comment]
Sorry, I was entering the wrong token.Att,Wellington
      
        
        
          On Sep 22 2023, at 10:18 am, Krut Patel ***@***.***> wrote:
          
        
        
          
@wmazoni try trakts plex --force again? And make sure the plex server url is correct

**Comment by iamkroot** [comment]
Closing this in favor of #234
