### ISSUE TITLE
Trakt Scrobbler grabs config for syncplay from /%appdata%/local only

### ISSUE THREAD

**Issue by Orski174** [iamkroot/trakt-scrobbler#172]
Grabs syncplay.ini from /appdata/local whilst syncplay non portable version stores syncplay.ini in /appdata/roaming

**Comment by iamkroot** [comment]
Thanks for creating the issue! Try out the solution mentioned in https://github.com/iamkroot/trakt-scrobbler/issues/171#issuecomment-1003852167, since it deals with a very similar situation (albeit, for vlc).
