### ISSUE TITLE
[BUG] Issue on installing on new Windows OS

### ISSUE THREAD

**Issue by GiacomoLaw** [iamkroot/trakt-scrobbler#18]
**Describe the bug**
Trying to install on a new PC, and getting this issue:

```
scripts\windows-install.bat
Checking config file
config.toml already exists in "C:\Users\giaco\AppData\Roaming\trakt-scrobbler\".
Please ensure that it matches sample_config.toml, or the app may crash unexpectedly.
ECHO is off.
Installing to "C:\Users\giaco\AppData\Local\trakt-scrobbler"
[pipenv.exceptions.LockfileNotFound]:   File "d:\python\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
[pipenv.exceptions.LockfileNotFound]:       return ctx.invoke(f, obj, *args, **kwargs)
[pipenv.exceptions.LockfileNotFound]:   File "d:\python\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
[pipenv.exceptions.LockfileNotFound]:       return callback(*args, **kwargs)
[pipenv.exceptions.LockfileNotFound]:   File "d:\python\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
[pipenv.exceptions.LockfileNotFound]:       return f(get_current_context(), *args, **kwargs)
[pipenv.exceptions.LockfileNotFound]:   File "d:\python\lib\site-packages\pipenv\cli\command.py", line 615, in sync
[pipenv.exceptions.LockfileNotFound]:       pypi_mirror=state.pypi_mirror,
[pipenv.exceptions.LockfileNotFound]:   File "d:\python\lib\site-packages\pipenv\core.py", line 2589, in do_sync
[pipenv.exceptions.LockfileNotFound]:       raise exceptions.LockfileNotFound("Pipfile.lock")
ERROR: Pipfile.lock not found! You need to run $ pipenv lock before you can continue.
 "Error while creating venv"
```

I have the exact repo in my downloads. How can I get it installed?

Thanks!

**Comment by iamkroot** [comment]
Thanks for bringing this to my attention! This should be fixed in the latest commit. Please try now :)

**Comment by GiacomoLaw** [comment]
Will do, thanks.

**Comment by iamkroot** [comment]
That is definitely not the case for me. Try a reboot?

**Comment by GiacomoLaw** [comment]
Still the exact same error :/

**Comment by spelworm** [comment]
Is this relevant to the issue at hand? https://github.com/pypa/pipenv/issues/3832

**Comment by GiacomoLaw** [comment]
I will try it with Python 3.6 - am using 3.7.

**Comment by GiacomoLaw** [comment]
Worked, thanks! Seems like pipenv has an issue with the latest releases of Python 3.7.

Thank you.

**Comment by GiacomoLaw** [comment]
Seems like it isn't running. When I run the program manually, it tells me the modules aren't installed, despite it installing fine.

**Comment by iamkroot** [comment]
> When I run the program manually, it tells me the modules aren't installed...

What modules?

**Comment by iamkroot** [comment]
@GiacomoLaw Any info?

**Comment by GiacomoLaw** [comment]
Apologies - been away till now - I'll try to get around to it soon. Thanks!

**Comment by GiacomoLaw** [comment]
Managed to install it, however trakt authentication no longer pops up. Is there any way I can manually add it?

**Comment by iamkroot** [comment]
> however trakt authentication no longer pops up.

That's because the auth is now persisted between installations. It probably detected the previous auth token and used it instead of prompting you.

**Comment by GiacomoLaw** [comment]
Okay, thanks. Where can I fond the programs logs?

**Comment by iamkroot** [comment]
The `%APPDATA%\trakt-scrobbler`folder contains the data files.

**Comment by GiacomoLaw** [comment]
Seems like it can't connect to VLC.

```
2019-08-07 07:55:54,981 - INFO - MainThread - scrobbler - Started scrobbler thread.
2019-08-07 07:55:55,014 - INFO - MainThread - monitor - Started monitor for vlc
2019-08-07 07:55:59,023 - INFO - vlc - monitor - Unable to connect to vlc. Ensure that the web interface is running.
```

![image](https://user-images.githubusercontent.com/9038673/62616498-9a87a000-b907-11e9-9211-4759a6c8e58d.png)

The password is just `password` - didn't change any settings.

![image](https://user-images.githubusercontent.com/9038673/62616514-a7a48f00-b907-11e9-86ff-f1087c7a7002.png)

Thanks!

**Comment by iamkroot** [comment]
Are you sure you've set the PORT properly? Read the `sample_config.toml` once and check your values accordingly. The `config.toml` will also be at `%APPDATA%\trakt-scrobbler`

**Comment by GiacomoLaw** [comment]
Yep, config shows `8080` as the port. Localhost shows it as up:

![image](https://user-images.githubusercontent.com/9038673/62713742-2297a380-b9f5-11e9-85df-ee53939fb924.png)

It seems like going to the `localhost:8080` has started making it work. When I switch my PC on again tomorrow I'll check to see if the tracker is still working without me having to go there first.

Getting this error when starting something:

![image](https://user-images.githubusercontent.com/9038673/62716966-eebf7c80-b9fa-11e9-9f3a-923e331b45d1.png)

Thanks!

**Comment by iamkroot** [comment]
Looks like you removed the `fileinfo` section from the config by mistake. Check the sample config once.

**Comment by GiacomoLaw** [comment]
That was it - working again! Thanks so much :D
