### ISSUE TITLE
[RFE] Release with github-actions

### ISSUE THREAD

**Issue by ahmubashshir** [iamkroot/trakt-scrobbler#181]
We can do this in a 2(or more, if anyone has other methods) ways:
1. Manually creating the release, steps:
   1. Bump version in pyproject.toml
   2. Commit, tag, push
   3. Create release
   4. Run `poetry publish` in workflow
2. Publishing release from tag, steps:
   1. Bump version in pyproject.toml
   2. Commit, tag, push
   3. Create release and `poetry publish` in workflow

**Comment by iamkroot** [comment]
Yeah, there's been a ~minor~ major hitch in this. Apparently, I set up 2FA for my PyPI account some time ago, and there's been a few mobile device changes since then. I don't see the site in my 2FA app, and PyPI says I haven't set up any recovery codes either. So I'm essentially locked out of my account :)

It's really weird though, I don't remember setting up 2FA on there. And if I did, I would have made sure to store the recovery codes in my password manager.

Seems like I'm gonna have to abandon the account on PyPI :/

**Comment by ahmubashshir** [comment]
BTW, you can test the workflow with [nektos/act](/nektos/act).

Required files:
```js
// event.json
{
   "ref": "refs/tags/v1.4.2"
}
```
```sh
# .secrets
PYPI_TOKEN="<PYPI_API_TOKEN"
```

then run `act -e event.json` to test the workflow.

**Comment by iamkroot** [comment]
Should we also add the aur release to the work flow?

**Comment by ahmubashshir** [comment]
Nope, because we'll have to setup an archlinux container to do that.
I'll add auto-updater to [pkgbuilds](/ahmubashshir/pkgbuilds) after my uni admission.

**Comment by iamkroot** [comment]
> we'll have to setup an archlinux container to do that.

Ah right, hadn't thought it through.


> P.S. Did you test the action?

Not yet, will try to get it done by this week. I guess it should be straightforward though - uploading to PyPI is simple. Plus I'm still waiting on the account recovery request, so won't be able to deploy for now.

**Comment by ahmubashshir** [comment]
> Ah right, hadn't thought it through.

I'll do that in my pkgbuilds repo, as all workflows there uses archlinux container. ETA 3 months, after my uni admission...

**Comment by ahmubashshir** [comment]
How's the situation with pypi now?

**Comment by iamkroot** [comment]
Sadly, no response from their team ;-;

**Comment by ahmubashshir** [comment]
Any update from them?

**Comment by iamkroot** [comment]
Nope, they haven't replied to any request since March. Will have to wait and see.

**Comment by iamkroot** [comment]
Hey @ahmubashshir finally got the account 2FA reset. Will try testing your PR with act first
