### ISSUE TITLE
[Feature Request] Option to disble continuous scrobbling

### ISSUE THREAD

**Issue by NePoCz** [iamkroot/trakt-scrobbler#187]
Would it be possible to have a setting to disable the "now watching" scrobbling and only have the script report once an item is watched? This will reduce the amount of notifications, wont load the Trakt API. I think that for some people, having the item marked as watched is the only important thing anyways

**Comment by iamkroot** [comment]
> This will reduce the amount of notifications

You can already do that with `trakts config set general.enable_notifs.scrobble false`. See [wiki](https://github.com/iamkroot/trakt-scrobbler/wiki/Configuration#enable_notifs).


> wont load the Trakt API

I would argue that is something the website owners should handle :P. Making tens of requests for a 20min episode is barely anything.
