### ISSUE TITLE
[QUESTION] What's the played progress percentage required for the scrobble to go through?

### ISSUE THREAD

**Issue by yolorag** [iamkroot/trakt-scrobbler#189]
I'm a little confused about the progress required for the scrobble to be completed. Is it possible to add configurable option to change it, or at least clarify the requirements for the scrobble to be completed? Sometimes I'm not getting them synced and I would like to know how to prevent it from happening.
I'm sure it's not not a problem with the recognition of media info since all the Linux isos are downloaded from the same completely legal torrent.

**Comment by iamkroot** [comment]
Trakt requires at least 80% progress for any file to be marked as "complete". If you're noticing that some scrobbles are missing I recommend that you consult your log file (`trakts log open`)

**Comment by yolorag** [comment]
@iamkroot thanks for clarification. I guess it may be an issue with my python installation since I somehow have two versions installed simultaneously.

**Comment by iamkroot** [comment]
If you want more help with your setup, please feel free to reopen and elaborate on your problem.
