### ISSUE TITLE
[Feature Request] Config to only scrobble either shows or movies

### ISSUE THREAD

**Issue by brijazz** [iamkroot/trakt-scrobbler#190]
I'm running trakt-scrobbler on a Mac and have my media in two folders:

```
Volumes/Plex/Plex TV
Volumes/Plex/Plex Movies
```

I only want to scrobble my TV views, so I've added the path to my whitelist by running `trakts whitelist add /Volumes/Plex/Plex\ TV`. My config reads:

```
fileinfo.whitelist = ['/Volumes/Plex/Plex TV']
general.enable_notifs = True
players.monitored = ['plex']
version = '1.0'
```

However (even after running `trakts start --restart`), movies are being scrobbled. Not sure if this is a bug or if I've just set up my whitelist incorrectly.

**Comment by iamkroot** [comment]
Unfortunately, the Plex monitor doesn't support whitelisting based on paths, since we get all the media info from Plex itself (and never see the file path).
I can consider adding the feature though, should be easy enough to implement. Will give it a shot when I have some time

**Comment by brijazz** [comment]
Great, would be a much-welcome feature. Thanks!

**Comment by brijazz** [comment]
Thanks for adding this! I don't think I've got it working, though. 

I ran: `trakts config set allowed_scrobbles movie:none`

As a result,  my config is now:

```
allowed_scrobbles = ['movie:none']
general.enable_notifs = True
players.monitored = ['plex']
version = '1.0'

Nonetheless, movies are being scrobbled.

```

**Comment by brijazz** [comment]
Thanks for adding this! I don't think I've got it working, though.

I ran: `trakts config set general.allowed_scrobbles.movie none`

As a result, my config is now:

```
general.enable_notifs = True
general.allowed_scrobbles.movie = 'none'
players.monitored = ['plex']
version = '1.0'
```

Nonetheless, movies are being scrobbled.

**Comment by iamkroot** [comment]
That's because the new version hasn't been released yet. If you are eager to try it out, follow these steps.
Install from branch:
1. Stop the scrobbler with `trakts stop`
2. Run `pipx install --force --pip-args='--force-reinstall' git+https://github.com/iamkroot/trakt-scrobbler.git`
3. Start scrobbler with `trakts start`

**Comment by brijazz** [comment]
Well, that would explain it! Updated per your instructions and movies are no longer being scrobbled, as expected. Thanks.
