### ISSUE TITLE
[BUG] Episodes scrobbled with MPC-HC are scrobbled double sometimes

### ISSUE THREAD

**Issue by CypherNL** [iamkroot/trakt-scrobbler#20]
**Describe the bug**
When competing an episode, trakt-scrobbler sometimes scrobble the same episode twice with a (less than a) 1 minute interval between those scrobbles.

**Desktop (please complete the following information):**
 - OS: Windows 10 1607 Enterprise LTSB 
 - Player: MPC-HC 32-bit
 - Player Version: 1.8.6
 - Trakt-scrobbler version: 43ec6d8b05cb77c7482644d674c05e970594963b (latest commit: scripts: Install pipenv automatically in script)

**To Reproduce**
1. Open a video file you want to play file
2. Play untill the episode is over, seek a 5 to 15 seconds back into during playing the video file. If the video file has chapters, skip to a chapter one or two times during playback.
3. Close the media player.
4. See the issue in the log file.

**Log file**
https://gist.github.com/CypherNL/c958041a131c3e5b4863998f251d4a13

**Comment by iamkroot** [comment]
It seems you have enabled both MPCHC and MPCBE for monitoring, and both the ports are same. This is causing both monitors to essentially detect the video being played. You should remove `mpcbe` from the monitored list in the config (`%APPDATA\trakt-scrobbler`), or, if you do use it, set a separate port for it.

**Comment by CypherNL** [comment]
I do see MPC-BE and HC in the config file active. Whoops.

Thanks for locating this issue. I will report when i scrobble something to see if it's solved or not.

**Comment by CypherNL** [comment]
It's solved! I've just scrobbled 6 episodes without any problems! Maybe you can note this in the instructions to only either enable MPC-HC or MPC-BE to make the scrobbler work with MPC-HC/BE.

**Comment by CypherNL** [comment]
See https://gist.github.com/CypherNL/80951ef4605a350257e435f22f6911d7 for my log output for 6 the 6 scrobbles.
