### ISSUE TITLE
[BUG] autostart on Windows

### ISSUE THREAD

**Issue by Sp3EdeR** [iamkroot/trakt-scrobbler#206]
**Describe the bug**

When running `trakts autostart enable`, it fails with `FileNotFoundError`, `[Errno 2] No such file or directory:`.

**Desktop (please complete the following information):**
 - OS and Version: Windows 11 22000.856
 - Python Version: 3.10.2
 - Player and Version: MPC-HC 1.9.21.1 (slightly modified personal fork, but generally the same)

**To Reproduce**

1. Change the location of Window's current user startup folder through the right click interface. This changes the path in the registry at `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders\Startup` to the new target location.
2. Run `trakts autostart enable`
3. Get the `FileNotFoundError`.

**Suggestion**

Use the path indicated by the above registry key instead of `start menu\Startup` to create the VBScript.

**Comment by Sp3EdeR** [comment]
Suggested solution (including winreg dependency) in `autostart.py`:
```
def get_autostart_serv_path() -> Path:
    ...
    else:
        from winreg import *
        key = OpenKey(ConnectRegistry(None, HKEY_CURRENT_USER), r"Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders")
        path = QueryValueEx(key, "Startup")[0]
        return Path(ret[0]) / (APP_NAME + ".vbs")
```

**Comment by iamkroot** [comment]
I'd be happy to accept a PR for this if you're interested :)

**Comment by Sp3EdeR** [comment]
The MPC-HC 1.9.21.1 web interface / variables page returns the following HTML document in UTF-8 encoding:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>MPC-HC WebServer - Variables</title>
        <link rel="stylesheet" href="default.css">
        <link rel="icon" href="favicon.ico">
    </head>
    <body class="page-variables">
        <p id="file">Példa Videó Név Ékezetekkel.avi</p>
        <p id="filepatharg">E:%5cLet%c3%b6lt%c3%a9sek%5cP%c3%a9lda%20Vide%c3%b3%20N%c3%a9v%20%c3%89kezetekkel.avi</p>
        <p id="filepath">E:\Letöltések\Példa Videó Név Ékezetekkel.avi</p>
        <p id="filedirarg">E:%5cLet%c3%b6lt%c3%a9sek</p>
        <p id="filedir">E:\Letöltések</p>
        <p id="state">1</p>
        <p id="statestring">Szünet</p>
        <p id="position">442</p>
        <p id="positionstring">00:00:00</p>
        <p id="duration">7786520</p>
        <p id="durationstring">02:09:47</p>
        <p id="volumelevel">100</p>
        <p id="muted">0</p>
        <p id="playbackrate">1</p>
        <p id="size">695 MB</p>
        <p id="reloadtime">0</p>
        <p id="version">1.9.21.1</p>

    </body>
</html>
```

Since the header states that this page is in utf-8, it seems correct to me.
