### ISSUE TITLE
[Installation] 

### ISSUE THREAD

**Issue by rafaelgirotti** [iamkroot/trakt-scrobbler#209]
### System Info
* Operating system and version: Windows 11
* Media Player and version: MPV (build from mpv.io)
* Python version: 3.10.6

### Description
My mpv.conf file is not on AppData. It is instead on Documents folder, is there a way to make trakts look for it in that folder?

### Log file

<details>
  <summary>Click to see log contents</summary>  
<p>

```
2022-09-07 03:15:44,334 - WARNING - MainThread - monitor - Failed to autoload value from 'C:\\Users\\girot\\AppData\\Roaming\\mpv\\mpv.conf': File not found
2022-09-07 03:15:44,334 - ERROR - MainThread - monitor - Config value autoload failed for mpv.
2022-09-07 03:15:44,335 - WARNING - MainThread - main - Could not start monitor for mpv
```

</p>
</details>

**Comment by iamkroot** [comment]
There is no way to do that currently. However, you can simply set the ipc path using the `trakts confing` command instead of trying to get it detected automatically. You can search closed github issues for the exact command, or try to piece it together from the wiki.

**Comment by rafaelgirotti** [comment]
I'm not sure what I'm supposed to put on the IPC path. The path to the mpv folder?

**Comment by iamkroot** [comment]
See [here](https://github.com/iamkroot/trakt-scrobbler/wiki/Players-Setup#ipc-path)

**Comment by iamkroot** [comment]
@rafaelgirotti Were you able to get it working?

**Comment by rafaelgirotti** [comment]
Yes, thank you!
