### ISSUE TITLE
[BUG]  Archlinux cleo from repository is api incompatible

### ISSUE THREAD

**Issue by ahmubashshir** [iamkroot/trakt-scrobbler#215]
Recently archlinux upgraded python-cleo to v1.0.0, which is api incompatible with v0.8.1, thus breaking trakt-scrobbler on archlinux (it was upgraded to satisfy dependency of python-poetry)

**Desktop (please complete the following information):**
 - OS and Version: Arch Linux
 - Python Version: 3.10.7
 - Player and Version: mpv 0.34.1-dirty

**To Reproduce**

1. run `trakts` from terminal
2. See error in log file

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
2022-10-09 11:57:57,456 - ERROR - MainThread - __init__ - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mubashshir/Documents/git/trakt-scrobbler/trakt_scrobbler/__main__.py", line 4, in <module>
    from .console import main
  File "/home/mubashshir/Documents/git/trakt-scrobbler/trakt_scrobbler/console.py", line 2, in <module>
    from cleo import Application
ImportError: cannot import name 'Application' from 'cleo' (/usr/lib/python3.10/site-packages/cleo/__init__.py)
2022-10-09 11:57:57,457 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
```
</p>
</details>

**Comment by iamkroot** [comment]
See https://github.com/iamkroot/trakt-scrobbler/issues/210

I won't be updating the dependency until cleo releases a stable version that actually has all the features we use today. Otherwise, I'll stay with 0.8.1. 

I suggest creating a `python-cleo-0.8.1` AUR repo instead.

**Comment by ahmubashshir** [comment]
That breaks poetry...

**Comment by iamkroot** [comment]
Yeah, this is why virtual envs were invented :)

**Comment by ahmubashshir** [comment]
On Sat, Oct 8 2022 at 11:10:49 PM -07:00:00, Krut Patel 
***@***.***> wrote:
> I won't be updating the dependency until cleo releases a stable 
> version that actually has all the features we use today. Otherwise, 
> I'll stay with 0.8.1.

Actually, you don't need to, I'm now testing it with v1-alpha, with a 
compatibility module...

	Mubashshir

**Comment by ahmubashshir** [comment]
I'll try handling this on aur end.
