### ISSUE TITLE
[BUG] Scrobbling Files with Multiple Episodes

### ISSUE THREAD

**Issue by george-emerald** [iamkroot/trakt-scrobbler#226]
**Describe the bug**

There's a bug handling files with multiple episodes (Mr.Robot.S02E01E02.) It starts scrobbling the first episode, when the second episode starts it starts scrobbling it but it doesn't stop scrobbling the first one so the first one doesn't show up in trakt's history.

**Desktop (please complete the following information):**
 - OS and Version: Mac OS 13.0.1
 - Python Version: 3.8.13
 - Player and Version: mpv 0.34.1

**To Reproduce**

1. Open a file that contains multiple episodes.
2. Both are scrobbled (show up as now playing), but only the second one is added to history.

**Log file**

Sadly, I don't have the file to play it and produce the log anymore.

**Comment by iamkroot** [comment]
Multi-eps are definitely supported by the app. In fact, I have played that exact episode (Mr Robot S02E01E02) and it worked just fine.

We can't do much without the logs. Does it happen with every multi-ep file, or just the one you mentioned? You could try temporarily renaming some random file to have multiple episodes, and then check the logs.

**Comment by george-emerald** [comment]
So, you're saying in your case it marked both episodes as watched and not just the second one like it did for me? I could try renaming a file, but doesn't the runtime have to match the runtime on trakt for it to work?

**Comment by iamkroot** [comment]
> So, you're saying in your case it marked both episodes as watched and not just the second one like it did for me?

Yep



> but doesn't the runtime have to match the runtime on trakt for it to work?

Nope, we only send the progress%, not the actual file duration. Any file will do.

**Comment by iamkroot** [comment]
Please reopen if still facing the issue
