### ISSUE TITLE
[BUG] "name 'Button' is not defined" error for command "trakts init"

### ISSUE THREAD

**Issue by ekk88d** [iamkroot/trakt-scrobbler#236]
**Describe the bug**

Hi, I just can't get the "trakts init" command to run without an error about a button not defined in notifier.py line 114
All of the details that I can gather are below.
Thanks for your help

**Desktop**
 - OS and Version: Windows 10, Powershell v7.3.1
 - Python Version: 3.9.7
 - Player and Version: Only player is MPC-BE w/listening enabled and 13679 port defined
 
 - Environment variables defined in PATH:
`C:\Users\<user>\AppData\Local\Programs\Python\Python39\Scripts\`
`C:\Users\<user>\AppData\Local\Programs\Python\Python39\`
`C:\Users\<user>\.local\bin (which has one file - trakts.exe)`

**To Reproduce**
1.  Run "trakts start"
2.  Trakt Scrobbler returns "The scrobbler is **_not_** running". Autostart does not work, nor does "trakts start --restart"
3.  Only Log file entry is 
`2022-12-30 19:34:25,769 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt`
4.  Run "trakts init"
5.  Trakt Scrobbler returns error below

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
NameError

  name 'Button' is not defined

  at ~\.local\pipx\venvs\trakt-scrobbler\lib\site-packages\trakt_scrobbler\notifier.py:114 in <module>
      110│     title=APP_NAME,
      111│     timeout=5,
      112│     stdout=False,
      113│     category="misc",
    → 114│     actions: Sequence[Button] = (),
      115│ ):
      116│     if stdout:
      117│         print(body)
      118│     if category not in enabled_categories:
```
</p>
</details>

Sidenote:
Windows 10 Notifications from apps are set to _On_.
Trakt Scrobbler is not listed in the apps/senders specified as notifications set to _Off_ or _On_.

**Comment by iamkroot** [comment]
Thanks for reporting this! I've fixed it in v1.6.2
