### ISSUE TITLE
[Installation] 

### ISSUE THREAD

**Issue by amphoterism** [iamkroot/trakt-scrobbler#243]
### System Info
* Operating system and version: Windows 11
* Media Player and version: VLC 3.0.18
* Python version: 3.11.1

### Description
Error when trying to install

### Command line output

```
PS C:\Users\rossn> trakts init
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

OSError

[WinError -2147024809] The parameter is incorrect

at AppData\Local\Programs\Python\Python311\Lib\site-packages\desktop_notifier\winrt.py:75 in init
71│ ) -> None:
72│ super().init(app_name, app_icon, notification_limit)
73│ self._appid = CoreApplication.get_id()
74│ self.manager = ToastNotificationManager.get_default()
→ 75│ self.notifier = self.manager.create_toast_notifier(self._appid)
76│
77│ async def request_authorisation(self) -> bool:
78│
79│ Request authorisation to send notifications.
```

### Log file

<details>
  <summary>Click to see log contents</summary>  
<p>

```
2023-02-16 16:51:15,935 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt

  Command: "trakts log open" or "trakts log path" or
  see [FAQ](https://github.com/iamkroot/trakt-scrobbler/wiki/FAQs#where-is-the-log-fileother-data-stored).
```
</p>
</details>

**Comment by iamkroot** [comment]
What version of the scrobbler are you using? It shouldn't happen in v1.6.3

**Comment by amphoterism** [comment]
<img width="425" alt="image" src="https://user-images.githubusercontent.com/29112371/219563155-478f8858-a844-4fad-9cc1-d07047b5fb40.png">

That's weird then... I'm on that version.

**Comment by iamkroot** [comment]
Hmm, that definitely shouldn't happen. Could you tell how you installed the app? Maybe you could try a clean install-
```
pipx uninstall trakt-scrobbler
pipx install trakt-scrobbler
```

**Comment by amphoterism** [comment]
I did a clean install on Python 3.11.1 and still got the message. I switched my python to 3.10 and re-installed and now it works.

**Comment by iamkroot** [comment]
Interesting, it should not be influenced by the python version. But glad that it is resolved for you.
I'll close this for now, if anyone else is facing this, feel free to leave a comment and we'll re-open it.
