### ISSUE TITLE
[BUG] If ipc server doesn't work correctly in Windows then why did you choose it over simple-web-ui 

### ISSUE THREAD

**Issue by aicynide** [iamkroot/trakt-scrobbler#247]
**Describe the bug**

A clear and concise description of what the bug/error is.

You have serious issue with coding, don't make us suffer for this. It never works if using portable_config. 
God setting it up is a torture

**Desktop (please complete the following information):**
 - OS and Version: Windows 11
 - Python Version: 3.11
 - Player and Version: mpv.latest

**To Reproduce**

1. Open '....' file
2. Play till '....'
3. Close player/pause it
4. See error in log file

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
(replace this line) *PASTE LOG FILE CONTENTS HERE* Command: "trakts log open" or "trakts log path"
```
</p>
</details>

**Comment by iamkroot** [comment]
Is this a bug report? Seems like a dup of #159

**Comment by aicynide** [comment]
What is the solution if not using %appdata%\mpv
