### ISSUE TITLE
Possible to scrobble what I'm watching on Plex app?

### ISSUE THREAD

**Issue by joloffz** [iamkroot/trakt-scrobbler#249]
I’m trying to get the scrobbler to acknowledge what I’m streaming on the Plex app on Chromecast or on my phone (from my PC) but I can’t get it to work. The directory for Plex is whitelisted and Plex is being monitored, it works great while I’m watching on Plex Media Player directly on PC. Any suggestions on how to make it work, if its even possible?

I did get an error message "Error while getting data from Plex: 503 server error: unavailable for for url: http://localhost:32400/status/sessions" after I set Plex to be monitored, but haven't got any more error messages since then.

**Comment by iamkroot** [comment]
Hmm I'm not fully sure why this is an issue. It shouldn't matter what device is playing the media, just that it should be visible from plex api. What do the scrobbler logs show?

**Comment by joloffz** [comment]
Yeah sorry, felt wrong putting it here in "issues", but didn't know where else to post it. Late response, but I got it working now! Feel free to delete this "issue" if possible. Thank you for such a useful program, good sir. I can't hardly imagine being without it.
