### ISSUE TITLE
Windows 11 notification crash

### ISSUE THREAD

**Issue by iamkroot** [iamkroot/trakt-scrobbler#259]
https://bit.ly/3QbHbdD

with the new push

_Originally posted by @panaris in https://github.com/iamkroot/trakt-scrobbler/issues/257#issuecomment-1756657481_

**Comment by iamkroot** [comment]
@panaris Let's continue here

**Comment by iamkroot** [comment]
I think there is some bug where old code is still showing up for some reason. I suggest 

1. Stop the scrobbler with `trakts stop`
2. Run `pipx uninstall trakt-scrobbler`
3. Run `pipx install git+https://github.com/iamkroot/trakt-scrobbler.git@master`
4. Start scrobbler with `trakts start`

**Comment by panaris** [comment]
Good call. that was indeed the problem. everything went right despite the strange errors.
https://bit.ly/3rQGAEK
WNDPROC return value cannot be converted to LRESULT
Apart from this everything is right except the scrobbler for mpc-be can't start because of this: (from the logs)
https://bit.ly/45zhV5g

**Comment by iamkroot** [comment]
Looks like a bug in the dependency we use to create notifications https://github.com/jithurjacob/Windows-10-Toast-Notifications/issues/117

There's some fixes for it but the repo is inactive. We will probably need to change to a more maintained library.
For now, you should be able to avoid this error by disabling all notifications from the config.

**Comment by panaris** [comment]
I also noticed that scrobble starts successfully but does not end when I stop watching or when the media ends, so it does not mark it as watched in trakt.
Many errors bellow:
https://bit.ly/494au9n

**Comment by iamkroot** [comment]
This seems to be related to the notifier issue- the traceback shows it errors out somewhere inside Win10Toast.

**Comment by panaris** [comment]
it's possible, because it shows no notifs other than the initial trakt one

**Comment by iamkroot** [comment]
Update: I'm looking into using a more up-to-date library for notifications on windows. Either `desktop-notifier` (that we already use for linux/mac) or `win11toast`. Both need us to set an App ID so Windows can show notifs. [This link](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast-other-apps) seems to be the closest to what we have.

**Comment by panaris** [comment]
https://pypi.org/project/Windows-Toasts/

this works for sure. i know because i follow closely another project

https://github.com/marticliment/WingetUI

**Comment by iamkroot** [comment]
@panaris Try reinstalling the master branch again. I've pushed a fix for this using `desktop-notifier`.

**Comment by panaris** [comment]
yes, it works now except button does nothing. i'll report any other issue i find

**Comment by iamkroot** [comment]
Please create a bug report for that!
(It is surprising, since the button JustWorks TM for me)

**Comment by panaris** [comment]
yes, button doesnt work but click works fine (except the console opening for a millisecond)

**Comment by ymyogev** [comment]
Getting this error when I do step 3 @iamkroot , what am I missing?
Sorry, not a Python-head

ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Cannot determine package name from spec 'git+https://github.com/iamkroot/trakt-scrobbler.git@master'. Check package
spec for errors.

> I think there is some bug where old code is still showing up for some reason. I suggest
> 
>     3. Run `pipx install git+https://github.com/iamkroot/trakt-scrobbler.git@master`

**Comment by panaris** [comment]
do you have git installed? https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
