### ISSUE TITLE
Iina can not get the scrobbler to work - macOS Sonoma 14.1 beta 3 

### ISSUE THREAD

**Issue by olivergiangvu** [iamkroot/trakt-scrobbler#261]
I got the Scrobbler work fine with Iina ( with a mpv config file) before.

Not use this for awhile then come back this week.

Do a refresh/reinstall to the newest version then I can't get it to work again - check all setting is fine ( trakt auth, ipc config,, whitelist...)

Please find my log attached. Thanks!
[trakt_scrobbler.log](https://github.com/iamkroot/trakt-scrobbler/files/13061428/trakt_scrobbler.log)
[trakt_scrobbler.log](https://github.com/iamkroot/trakt-scrobbler/files/13061429/trakt_scrobbler.log)

**Comment by iamkroot** [comment]
Could you share a few examples of the kind of files that are failing to scrobble? From your logs, I see that some files _did_ get scrobbled (Malum, Jade The Invisible) a few months ago.

Also, try `trakts test mpv`

**Comment by olivergiangvu** [comment]
> Could you share a few examples of the kind of files that are failing to scrobble? From your logs, I see that some files _did_ get scrobbled (Malum, Jade The Invisible) a few months ago.
> 
> Also, try `trakts test mpv`
below is mine whitelist
https://*.debrid.it/*
https://*.fshare.vn/*
https://*.fshare.vn/*/*
https://*.fshare.vn/dl/*
https://*.fshare.vn/dl/*/*
https://*.fshare.vn/dl/*/*/*
https://torrentio.strem.fun/alldebrid/*/*/*

the fshare.vn never worked before but I use kodi and it still can scrobble 
Mainly before I use thí to scrobble link from debrid ( now only alldebrid) and link from Torrentio from Stremio with Iina as default external player.

**Comment by olivergiangvu** [comment]
![CleanShot 2023-10-23 at 01 48 47@2x](https://github.com/iamkroot/trakt-scrobbler/assets/106240777/3661cb43-9648-4aee-9fe9-7b018ac54e9c)
I try the  trakts test mpv  it get back as time out 
[trakt_scrobbler.log](https://github.com/iamkroot/trakt-scrobbler/files/13064297/trakt_scrobbler.log)
The mpv config file
![CleanShot 2023-10-23 at 01 53 11@2x](https://github.com/iamkroot/trakt-scrobbler/assets/106240777/23084ffc-278c-40cb-aa21-6fdb57e9edfc)
![CleanShot 2023-10-23 at 01 53 54@2x](https://github.com/iamkroot/trakt-scrobbler/assets/106240777/ba0a5cc1-cce5-4853-93ec-f1660d407412)

**Comment by olivergiangvu** [comment]
I did try the same link on vlc - also not work

**Comment by olivergiangvu** [comment]
https://lpzdz4.debrid.it/dl/2wg335d7cae/Bodies.S01E01.Siete.gia.morto.allora.ITA.ENG.1080p.NF.WEB-DL.DDP5.1.Atmos.H.264-MeM.GP.mkv

![CleanShot 2023-10-23 at 02 07 51@2x](https://github.com/iamkroot/trakt-scrobbler/assets/106240777/e96b73ba-0771-40b8-8adf-068adda6dcb1)
[trakt_scrobbler.log](https://github.com/iamkroot/trakt-scrobbler/files/13064371/trakt_scrobbler.log)
This link get directly from alldebrid ( by Wako tv app) also not work.

**Comment by iamkroot** [comment]
I'm not sure if this is a vlc/mpv issue or a stream issue. Here's how we can find out- could you try first downloading one of the files and then playing from the local path? See if that is detected.

**Comment by olivergiangvu** [comment]
I did try to downloaded the file then play back but it still not work.

![CleanShot 2023-10-24 at 13 14 26](https://github.com/iamkroot/trakt-scrobbler/assets/106240777/98ba8012-e09d-4ccc-a0c2-f65f163a7bc3)
[trakt_scrobbler.log](https://github.com/iamkroot/trakt-scrobbler/files/13111339/trakt_scrobbler.log)

**Comment by olivergiangvu** [comment]
vlc is working
![CleanShot 2023-10-24 at 13 18 23](https://github.com/iamkroot/trakt-scrobbler/assets/106240777/d70056cb-58c1-437f-b7ca-935740ccaf7d)

**Comment by iamkroot** [comment]
Hmm, it seems something might be improper with the mpv connection. Let's try this-
1. Play some file in iina
2. Open the terminal, and run `echo '{ "command": ["get_property", "playback-time"] }' | socat - /tmp/mpvsocket`
3. It should return some success message if mpv is accessible via iina.

**Comment by olivergiangvu** [comment]
I try but no message respond.
I guess somethign happen and the scrobble can connect to the  ipc server anymore.
![CleanShot 2023-10-24 at 15 59 11](https://github.com/iamkroot/trakt-scrobbler/assets/106240777/5bdfd3e7-5d70-4259-aaac-2e92fc7a7899)

**Comment by olivergiangvu** [comment]
I make it worked now.
Somehow new ver of Iina not seem work with config file but can input as mpv option and it work
![CleanShot 2023-10-24 at 22 02 57](https://github.com/iamkroot/trakt-scrobbler/assets/106240777/99937c8d-ff32-4e0f-be0e-4c64d4876dd0)
![CleanShot 2023-10-24 at 22 05 16](https://github.com/iamkroot/trakt-scrobbler/assets/106240777/09587476-5725-4068-bc2f-4ccb4b3e3a72)
Thank so much for your assist!

**Comment by iamkroot** [comment]
Awesome! Glad it worked out.

A side note- many of your private passwords (vlc) and tokens (trakt) are visible in the log files that you have uploaded. I would highly recommend changing the passwords since the files have most likely already been archived by bots (deleting won't help
