### ISSUE TITLE
[Installation] Not working on Arch Linux (Garuda)

### ISSUE THREAD

**Issue by ALi3naTEd0** [iamkroot/trakt-scrobbler#263]
### System Info
* Operating system and version: Garuda Linux KDE
* Media Player and version: Not tested yet
* Python version: 3.11.5

### Description
I'm getting this error: `marked out of date: python-cleo-v0 python-urlmatch :: orphans: python-cleo-v0` when trying to install no matter if I clone the [git](https://aur.archlinux.org/packages/trakt-scrobbler) or do `paru -S trakt-scrobbler` so it seems like it needs a fix also previously [flagged here](https://aur.archlinux.org/pkgbase/trakt-scrobbler/flag-comment). _(Also tried installing dependencies separately with the same result)_

### Command line output
Input 1
``` 
git clone https://aur.archlinux.org/trakt-scrobbler.git
cd trakt-scrobbler
makepkg -si
```
Output
```
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
-> python-guessit<4.0.0
-> python-guessit>=3.3.1
-> python-appdirs<2.0.0
-> python-appdirs>=1.4.4
-> python-confuse<3.0
-> python-confuse>=2.0
-> python-pydantic<2.0.0
-> python-setuptools<66.0.0
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```
Input 2
```
paru -S trakt-scrobbler
```
Output
```
:: marked out of date: python-cleo-v0 python-urlmatch
:: orphans: python-cleo-v0
```
### Dependencies
```
sudo pacman -S python-pydantic<2.0.0 python-setuptools<66.0.0
```

### Log file

<details>
  <summary>Click to see log contents</summary>  
<p>

```
```
</p>
</details>

**Comment by dontna** [comment]
Can confirm the issue! You can do a workaround by manually installing the python packages using 'pip' and then editing the PKGBUILD to remove all of the python packages under 'depends' and just leave 'systemd' there.

It would look something like:

**Install the packages using pip**
`pip install guessit appdirs confuse pydantic setuptools`

**Open the PKGBUILD**
`vim PKGBUILD`

**Remove the python deps**
```
depends=(
	"systemd"
	'python-requests<3.0.0' #auto-deps
	'python-requests>=2.25.1' #auto-deps
	'python-urllib3<2.0.0' #auto-deps
	'python-urllib3>=1.26.0' #auto-deps
	'python-guessit<4.0.0' #auto-deps
	'python-guessit>=3.3.1' #auto-deps
	'python-appdirs<2.0.0' #auto-deps
	'python-appdirs>=1.4.4' #auto-deps
	'python-cleo-v0<0.9.0' #auto-deps
	'python-cleo-v0>=0.8.1' #auto-deps
	'python-confuse<3.0' #auto-deps
	'python-confuse>=2.0' #auto-deps
	'python-urlmatch<2.0.0' #auto-deps
	'python-urlmatch>=1.0.1' #auto-deps
	'python-pydantic<2.0.0' #auto-deps
	'python-pydantic>=1.10.2' #auto-deps
	'python-setuptools<66.0.0' #auto-deps
	'python-setuptools>=65.5.1' #auto-deps
)
```

_It should look like:_ 
```
depends=(
	"systemd"
)
```

Then just save the file.

The workaround works for me, until we wait for the issue to be fixed!

**Comment by ALi3naTEd0** [comment]
> Can confirm the issue! You can do a workaround by manually installing the python packages using 'pip' and then editing the PKGBUILD to remove all of the python packages under 'depends' and just leave 'systemd' there.
> 
> It would look something like:
> 
> **Install the packages using pip** `pip install guessit appdirs cleo confuse urlmatch pydantic setuptools`
> 
> **Open the PKGBUILD** `vim PKGBUILD`
> 
> **Remove the python deps**
> 
> ```
> depends=(
> 	"systemd"
> 	'python-requests<3.0.0' #auto-deps
> 	'python-requests>=2.25.1' #auto-deps
> 	'python-urllib3<2.0.0' #auto-deps
> 	'python-urllib3>=1.26.0' #auto-deps
> 	'python-guessit<4.0.0' #auto-deps
> 	'python-guessit>=3.3.1' #auto-deps
> 	'python-appdirs<2.0.0' #auto-deps
> 	'python-appdirs>=1.4.4' #auto-deps
> 	'python-cleo-v0<0.9.0' #auto-deps
> 	'python-cleo-v0>=0.8.1' #auto-deps
> 	'python-confuse<3.0' #auto-deps
> 	'python-confuse>=2.0' #auto-deps
> 	'python-urlmatch<2.0.0' #auto-deps
> 	'python-urlmatch>=1.0.1' #auto-deps
> 	'python-pydantic<2.0.0' #auto-deps
> 	'python-pydantic>=1.10.2' #auto-deps
> 	'python-setuptools<66.0.0' #auto-deps
> 	'python-setuptools>=65.5.1' #auto-deps
> )
> ```
> 
> _It should look like:_
> 
> ```
> depends=(
> 	"systemd"
> )
> ```
> 
> Then just save the file.
> 
> The workaround works for me, until we wait for the issue to be fixed!

Yes, forgot to share that also got it working using `pipx` mentioned [here](https://aur.archlinux.org/packages/trakt-scrobbler#comment-943649):
```
sudo pacman -S python-pipx
pipx install trakt-scrobbler
pipx ensurepath
pipx run trakt-scrobbler
trakts
```

**Comment by iamkroot** [comment]
Yup, `pipx` is the recommended way to install.
