### ISSUE TITLE
[FR] Adding delay to autostart

### ISSUE THREAD

**Issue by ALi3naTEd0** [iamkroot/trakt-scrobbler#267]
So, basically I was getting this annoying message at system startup, so I created a "trakt-scrobbler.timer" file where "trakt-scrobbler.service" is, to add a 1-minute delay... just wanted to share it because it might be useful to somebody else trying to accomplish the same... 

```
# ~/.config/systemd/user/trakt-scrobbler.timer
[Unit]
Description=Delay start of trakt-scrobbler service

[Timer]
OnBootSec=1min
OnUnitActiveSec=1min

[Install]
WantedBy=default.target
```

Tested on Garuda Linux, should work on other operating systems with the correct paths I guess? Anyway, hope it helps.

**Comment by iamkroot** [comment]
> I was getting this annoying message at system startup

What was the message? I have no issues with the default service on Arch Linux.
