### ISSUE TITLE
[BUG] Trakts gives error after ubuntu 20-22-23 upgrade

### ISSUE THREAD

**Issue by yeyogrande** [iamkroot/trakt-scrobbler#274]
After upgrade from Ubuntu 20.xx to 22.xx then on to 23.10, I can't run trakts. I think this is some type of path or env (or venv or pip(x) or python version? thing. 

Re-cap after solving:
This was in fact a problem with my python environment.  I uninstalled pip, pipx, python, and deleted the .local/pipx folder. This may have been overkill with all the removing, I might have just been fine with just removal of only pip or both pip/pipx. Being inexperienced in Python environments I did not know that the following error was not a problem. 

error: externally-managed-environment

This environment is externally managed
 To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
 
I also was getting this error below indicating there was a problem with pip:

me@mybox:~$ pipx install trakt-scrobbler
Fatal error from pip prevented installation. Full pip output in file:
    /home/me/.local/pipx/logs/cmd_2024-01-16_18.43.58_pip_errors.log

/home/me/.local/pipx/venvs/trakt-scrobbler/bin/python: No module named pip

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
(replace this line) *PASTE LOG FILE CONTENTS HERE* Command: "trakts log open" or "trakts log path"
```
</p>
</details>

**Comment by iamkroot** [comment]
Maybe try to uninstall and install again? Might have something to do with your python/pipx being upgraded.

**Comment by yeyogrande** [comment]
1.Cheers. Please advise I amkroot. Uninstall reinstall not working. You have not responded to my above request of needing your guidance on whether I should uninstall reinstall pip. Maybe my fault as I pasted log file into above issue instead of making new comment.

2.If  I need to, what is exact command to uninstall reinstall pip correctly?  I fear I will screw up other python programs as I am not very Python environment savy so I do not want to jump the gun and make a mistake I will regret. What do they say better safe than .....

3. What does the log file:  /home/me/.local/pipx/logs/cmd_2024-01-16_18.43.58_pip_errors.log attached above mean?

Specifically this part: /home/me/.local/pipx/venvs/trakt-scrobbler/bin/python: No module named pip

4. Also from above issue. Is this part correct the error part ? 
python3 -m pip install --user pipx

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.  etc etc see above. 

What does error mean. It has been long time since I messed with these python/pip/pipx env/venv matters and I am feeling a little lost. Or maybe a lot lost. Good Day mate. Best Regards Always :)

**Comment by yeyogrande** [comment]
When also trying to fix plextraktsync, which I  feel is broke for the same python pip pipx environment issue reason as trakts. I get same error below Really need to know how to scrap everything python wise if this is possible but python list or pipx/pip list shows lots of installed programs so I dont know how to go about jettisoning the whole lot without gigantic system wide headache :)

python3 -m pip install --user --upgrade pipx
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

**Comment by yeyogrande** [comment]
So yeah ran those again. pip list and pipx list. I get ton of pkgs with pip list. And pipx list gives:

pipx list
venvs are in /home/me/.local/pipx/venvs
apps are exposed on your $PATH at /home/stax/.local/bin
⚠️  package PlexTraktSync has missing internal pipx metadata.

One or more packages have a missing internal pipx metadata.
   They were likely installed using a pipx version before 0.15.0.0.
   Please uninstall and install these package(s) to fix.

and this 
pipx install PlexTraktSync
Fatal error from pip prevented installation. Full pip output in file:
    /home/me/.local/pipx/logs/cmd_2024-01-19_07.33.36_pip_errors.log

Error installing plextraktsync.

Dont know if this helps just thought I would include it. Cheers :)

**Comment by yeyogrande** [comment]
Got no responses on this. So I went ahead and deleted trakts, pipx, pip, (and plextraktsync) and all related files in .local dir. Will report back results of reinstalling tomorrow.

**Comment by yeyogrande** [comment]
Iamkroot thanks again for sharing your code with everyone. I do love the program and I  hope to examine your code in the future after I start reading the python book. Delete this whole ticket if you feel it does not belong in this forum, I realize that it is a python env problem not a trakts problem. Or leave it if you think it could possibly help someone in the same situation as me. I tried to clean it up for archiving purposes but I do not see where the BOLD markup tags are. Also thanks for letting me stew on it for awhile and get a small bit of a lesson. Peace.

**Comment by yeyogrande** [comment]
Closing issue.
