### ISSUE TITLE
[Installation] I can't find remap_rules.toml

### ISSUE THREAD

**Issue by Seyferto** [iamkroot/trakt-scrobbler#277]
Why refer to a file that doesn't seem to exist? I downloaded a zip of all the files here and it still doesn't seem to be there...

ps. I created it myself, which it seems to detect since it errored a bit, but it still can't seem to find the title and update it, so... match.title needs to have what, the exact file's name? Folder name? Just the generic, common name? I seem to be having this problem due to the name having an acronym with periods in between...

**Comment by iamkroot** [comment]
First off, media remap is an advanced feature. Are you sure you need it? Can you rename the files (use something like filebot) and get it to work? 

Answering your questions: Title is the media title (the one that is embedded in your video file). Path is the file path on disk or the url if streaming. You should be matching on one of those.

**Comment by iamkroot** [comment]
See https://github.com/iamkroot/trakt-scrobbler/pull/214#issuecomment-1272374298 for a detailed example

**Comment by Seyferto** [comment]
How can you ask if it's needed when nearly everything I watch seems to be undetected...? This tool could certainly try to find titles more accurately, as I've no idea why even it's happening... first series had periods in them, so I assumed that is why it's not detected, but another series had none, just a number and a word, so now I'm wondering whether it can detect numbers...
