### ISSUE TITLE
[Installation]

### ISSUE THREAD

**Issue by aditya-029** [iamkroot/trakt-scrobbler#282]
❯ trakts init
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

  AttributeError

  module 'pkgutil' has no attribute 'ImpImporter'

  at .local/pipx/venvs/trakt-scrobbler/lib/python3.12/site-packages/pkg_resources/__init__.py:2191 in <module>
      2187│     dist_groups = map(find_distributions, resolved_paths)
      2188│     return next(dist_groups, ())
      2189│
      2190│
    → 2191│ register_finder(pkgutil.ImpImporter, find_on_path)
      2192│
      2193│ if hasattr(importlib_machinery, 'FileFinder'):
      2194│     register_finder(importlib_machinery.FileFinder, find_on_path)
      2195│

**Comment by iamkroot** [comment]
Dup of #257
