### ISSUE TITLE
[Installation] 'trakts init' fails

### ISSUE THREAD

**Issue by kgeo** [iamkroot/trakt-scrobbler#296]
### System Info
* Operating system and version: Windows 10
* Media Player and version: mpv 1c9c2f5
* Python version: 3.12

### Description
trakts init does not run

### Command line output
PS C:\Users\x> trakts init
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

  AttributeError

  module 'pkgutil' has no attribute 'ImpImporter'

  at pipx\venvs\trakt-scrobbler\Lib\site-packages\pkg_resources\__init__.py:2191 in <module>
      2187│     dist_groups = map(find_distributions, resolved_paths)
      2188│     return next(dist_groups, ())
      2189│
      2190│
    → 2191│ register_finder(pkgutil.ImpImporter, find_on_path)
      2192│
      2193│ if hasattr(importlib_machinery, 'FileFinder'):
      2194│     register_finder(importlib_machinery.FileFinder, find_on_path)
      2195│
### Log file

<details>
  <summary>Click to see log contents</summary>  
<p>

```
(replace these lines) *PASTE LOG FILE CONTENTS HERE*
  Command: "trakts log open" or "trakts log path" or
  see [FAQ](https://github.com/iamkroot/trakt-scrobbler/wiki/FAQs#where-is-the-log-fileother-data-stored).
```
</p>
</details>

**Comment by iamkroot** [comment]
See #257
