### ISSUE TITLE
[BUG] trakts init error | malformed regex: 'https://www.youtube.com/watch?*'

### ISSUE THREAD

**Issue by ang3lo-azevedo** [iamkroot/trakt-scrobbler#302]
**Describe the bug**

Error on trakts init

**Desktop (please complete the following information):**
 - OS and Version: Arch 6.9.3-arch1-1
 - Python Version: Python 3.12.3

**To Reproduce**

1. Install
2. Write the 'trakts init' command

This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

  ConfigValueError

  fileinfo.exclude_patterns#0: malformed regex: 'https://www.youtube.com/watch?*'. Error: multiple repeat at position 30

  at .local/share/pipx/venvs/trakt-scrobbler/lib/python3.12/site-packages/confuse/templates.py:87 in fail
       83│         """
       84│         exc_class = (
       85│             exceptions.ConfigTypeError if type_error
       86│             else exceptions.ConfigValueError)
    →  87│         raise exc_class(u'{0}: {1}'.format(view.name, message))
       88│ 
       89│     def __repr__(self):
       90│         return '{0}({1})'.format(
       91│             type(self).__name__,

**Comment by iamkroot** [comment]
Any particular reason you've added youtube to `exclude_patterns`? You'd only need to exclude something if there's a more general rule present in the `whitelist` (for example, if you wanted to allow all videos from `https://my.cool.site.example.org/` EXCEPT the ones from `https://my.cool.site.example.org/secret-stuff/` - you'd put the first one in whitelist and the second one in exclude). It doesn't make sense to exclude the entirety of youtube - you needn't put it in the whitelist in the first place.

To edit this, you would have to edit the trakt config file (see https://github.com/iamkroot/trakt-scrobbler/wiki/FAQs#where-is-the-log-fileother-data-stored) and remove the part from `fileinfo.exclude_patterns`

**Comment by BrutuZ** [comment]
All in all, it *is* [invalid RegEx](https://regexr.com). With the `?` you're asking for "one or none" of the previous character (the `h` at the end), the `*` would ask "one or many" of the previous character, hence the multiple repeat error.
You could have `*?` instead to make it "none or many lazily", but still wouldn't be what you want since it would match `.../watc`, `.../watch`, `.../watchhhhh`

Seem like you mixed RegEx and Globbing somehow

**Comment by iamkroot** [comment]
Closing this, config issue.
