### ISSUE TITLE
[Feature Request] Sync trakt scrobbled resume point to media player

### ISSUE THREAD

**Issue by em-r-c** [iamkroot/trakt-scrobbler#307]
**Describe the Feature**

Would it be possible to use the Web UI controls of (some) local player(s) to sync the scrobbled resume point from trakt? This would enable programmatic seemless playback across multiple devices

**Desktop (please complete the following information):**
 - OS and Version: Windows 11
 - Python Version: 3.11
 - Player and Version: mpc-hc 2.1.7.2
 - Trakt Scrobbler Version: 1.6.3

**Comment by iamkroot** [comment]
Hmm, while the feature would be nice, it is likely not going to be implemented in this scrobbler. We only want to worry about taking events from player and sending them to trakt.

Going the other way, trying to control the player opens up another can of worms that I am not sure I have the bandwidth for. This would be best implemented in a separate utility.
