### ISSUE TITLE
Stremio's Building MPV

### ISSUE THREAD

**Issue by bramdsgn** [iamkroot/trakt-scrobbler#317]
Stremio has MPV running under the hood and I wanted the LIVE Scrobbling provided by trakt-scrobbler and the "resume watching feature" from Stremio (you don't get to have that with MPV as an external Player)
so i guess i wanted the best of both worlds, is it possible ?

**Comment by wasi-master** [comment]
doesn't stremio also have live scrobbling?

**Comment by iamkroot** [comment]
Yeah, Stremio comes with Trakt integration built-in. I recently started using it, and seems mostly usable. 

Are there any particular features of our package that are missing from the Stremio plugin?

I would rather contribute upstream than try to duplicate effort here.
