### ISSUE TITLE
Issue using Python 3.8 with trakt-scrobbler.

### ISSUE THREAD

**Issue by geekcatfr** [iamkroot/trakt-scrobbler#35]
I'm using Win10, i have downloaded Python 3.8 and all requierements (config file is good etc etc), but the main.py crashes at launch. When i try to launch it with the terminal i got this error :

`C:\Users\Geekcat\AppData\Local\trakt-scrobbler>pipenv run python main.py                                                Traceback (most recent call last):                                                                                        File "main.py", line 11, in <module>                                                                                      from scrobbler import Scrobbler                                                                                       File "C:\Users\Geekcat\AppData\Local\trakt-scrobbler\scrobbler.py", line 4, in <module>                                   from notifier import notify                                                                                           File "C:\Users\Geekcat\AppData\Local\trakt-scrobbler\notifier.py", line 9, in <module>                                    from win10toast import ToastNotifier                                                                                  File "C:\Users\Geekcat\.virtualenvs\trakt-scrobbler-PdssKQCW\lib\site-packages\win10toast\__init__.py", line 19, in <module>                                                                                                                      from win32api import GetModuleHandle                                                                                ImportError: DLL load failed while importing win32api: Le module spécifié est introuvable. `

i look on internet and i found this : https://stackoverflow.com/questions/58631512/pywin32-and-python-3-8-0

**Comment by GMFalka** [comment]
I had the same problem. You need to manually install win32api module with admin rights.

[Try this comment](https://stackoverflow.com/a/27196622)

**Comment by geekcatfr** [comment]
> 
> 
> I had the same problem. You need to manually install win32api module with admin rights.
> 
> [Try this comment](https://stackoverflow.com/a/27196622)

i tried but i have the same error

**Comment by iamkroot** [comment]
> i tried but i have the same error

Were you successfully able to run the post_install script mentioned in the answer?

**Comment by GMFalka** [comment]
uninstall win32api from cmd, then reinstall with cmd admin rights.

**Comment by geekcatfr** [comment]
> 
> 
> > i tried but i have the same error
> 
> Were you successfully able to run the post_install script mentioned in the answer?

nope. crashing at finish device authentication. i can't see the error, the cmd closes after it

**Comment by GMFalka** [comment]
> > > i tried but i have the same error
> > 
> > 
> > Were you successfully able to run the post_install script mentioned in the answer?
> 
> nope. crashing at finish device authentication. i can't see the error, the cmd closes after it

Check and copy the log (`\AppData\Roaming\trakt-scrobbler`) to here

**Comment by geekcatfr** [comment]
> 
> 
> > > > i tried but i have the same error
> > > 
> > > 
> > > Were you successfully able to run the post_install script mentioned in the answer?
> > 
> > 
> > nope. crashing at finish device authentication. i can't see the error, the cmd closes after it
> 
> Check and copy the log (`\AppData\Roaming\trakt-scrobbler`) to here

the log is empty.

**Comment by iamkroot** [comment]
Hey @geekcatfr all I can suggest for now is to use Python3.7 for now. You can download that from the website, uninstall 3.8, including the folder in `C:\Users\username\.virtualenvs\trakt-scrobbler-xxxxxxxx` and run the install script again.

**Comment by GMFalka** [comment]
> > > i tried but i have the same error
> > 
> > 
> > Were you successfully able to run the post_install script mentioned in the answer?
> 
> nope. crashing at finish device authentication. i can't see the error, the cmd closes after it

To see the error, open a cmd window, cd into the install.bat location and then run the bat. The window will stay open even after the crash so we can see wheres the problem.

Like this:

_C:\Users\username>_**cd C:\Users\username\Desktop\trakt-scrobbler-master**

_C:\Users\username\Desktop\trakt-scrobbler-master>_**windows-install.bat**

**Comment by iamkroot** [comment]
Hey @geekcatfr. I just tried using Python 3.8 on a Windows 10 machine and it seems to work fine, no hiccups during install. I guess the dependencies that were breaking have been updated properly.
