### ISSUE TITLE
[question] Editing whitelist after installation

### ISSUE THREAD

**Issue by MannixMD** [iamkroot/trakt-scrobbler#37]
This may be a dumb question but Can I add additional paths to the whitelist after the installation?

**Comment by iamkroot** [comment]
> This may be a dumb question

Not at all!

> Can I add additional paths to the whitelist after the installation?

Yes, that is indeed possible. You just need to edit `config.toml` from the data directory. For Windows, it will be inside `C:\Users\<YourName>\AppData\Roaming\trakt-scrobbler\`. (To open, press `Win + R` and enter `%APPDATA%\trakt-scrobbler`). After editing, you'll have to reboot your system for the changes to take effect.

I should probably clarify this part in the README. Thanks for taking the time to create an issue!
