### ISSUE TITLE
[HELP WANTED] Unable to install on Mac Catalina

### ISSUE THREAD

**Issue by prabapro** [iamkroot/trakt-scrobbler#41]
**Describe the bug**
I cannot install on my Mac. Please help. Thank you.

`Prabas-MacBook-Air:tools codechilli$ python3 install.py
Starting installation for trakt-scrobbler
Traceback (most recent call last):
  File "install.py", line 225, in <module>
    main()
  File "install.py", line 204, in main
    source_dir, install_dir, cfg_dir = get_default_paths()
  File "install.py", line 40, in get_default_paths
    install_dir.mkdir(exist_ok=True, parents=True)
AttributeError: 'tuple' object has no attribute 'mkdir'
Prabas-MacBook-Air:tools codechilli$`

![image](https://user-images.githubusercontent.com/32594937/72007344-78f46100-3277-11ea-95dc-747ac986b88a.png)

**Desktop:**
 - OS: MacOS Catalina
 - Python Version: 3.8.1
 - Player :VLC, MPV,PLEX
 - Player Version: VLC 3.0.6 Vetinari

**Comment by iamkroot** [comment]
Hey @prabapro, I've updated the installer to fix this. Give it a try again.

**Comment by prabapro** [comment]
Hey @iamkroot ,

Thanks a lot for the quick fix. Appreciate it.

Getting below error. Please help. Thanks heaps mate. 

![image](https://user-images.githubusercontent.com/32594937/72140070-edcdb500-33b5-11ea-83d8-444914205142.png)

**Comment by GMFalka** [comment]
> Hey @iamkroot ,
> 
> Thanks a lot for the quick fix. Appreciate it.
> 
> Getting below error. Please help. Thanks heaps mate.

Had the same problem, what helped me is: 
Manually remove and install poetry.

**Comment by prabapro** [comment]
> > Hey @iamkroot ,
> > Thanks a lot for the quick fix. Appreciate it.
> > Getting below error. Please help. Thanks heaps mate.
> 
> Had the same problem (on linux) what helped me is:
> Manually remove and install poetry, then run the installer.
> That might be a stupid help, because the installer is ran in a venv..

Hey @GMFalka Thank you for your reply. Tried uninstalling the poetry & reinstalled. Still same error...

**Comment by GMFalka** [comment]
> > > Hey @iamkroot ,
> > > Thanks a lot for the quick fix. Appreciate it.
> > > Getting below error. Please help. Thanks heaps mate.
> > 
> > 
> > Had the same problem (on linux) what helped me is:
> > Manually remove and install poetry, then run the installer.
> > That might be a stupid help, because the installer is ran in a venv..
> 
> Hey @GMFalka Thank you for your reply. Tried uninstalling the poetry & reinstalled. Still same error...

@iamkroot probably your best chance, but while you wait: 
Poetry is installed to different user then where the installer wants it to. 
In cli try the poetry version check command, if it doesn't find poetry either you can go from there.

**Comment by prabapro** [comment]
@iamkroot 
![image](https://user-images.githubusercontent.com/32594937/72145095-bf54d780-33bf-11ea-86ab-126c65ccf44c.png)

**Comment by iamkroot** [comment]
Thanks for pitching in @GMFalka! @prabapro This looks like a separate issue. It'll be simpler to treat is as such.
