### ISSUE TITLE
installation problem - raspbian

### ISSUE THREAD

**Issue by ConzzTV** [iamkroot/trakt-scrobbler#43]
When I run install.py I'm only getting this error:

```
  File "install.py", line 12
    def print_quit(*msg, status=1):
                              ^
SyntaxError: invalid syntax
```

And I don't think that this is the only error due to other outputs in the Python interface...
My Python version is 3.7

**Comment by iamkroot** [comment]
@ConzzTV You are most likely running the script with python2. Run it as `python3 install.py`
