### ISSUE TITLE
Install.py requires poetry (Windows 10)

### ISSUE THREAD

**Issue by nvvasilev** [iamkroot/trakt-scrobbler#44]
Hi @iamkroot,

After running `python install.py` I get the following log in the console: 

![image](https://user-images.githubusercontent.com/12248943/72201168-f24ba980-3459-11ea-805c-aa4681746ccb.png)

I installed `poetry` using the `get-poetry.py` script, I check if the environment Path is updated and then I restart the console and try again but I get the same result.

User environment variables:

![image](https://user-images.githubusercontent.com/12248943/72201436-a6e6ca80-345c-11ea-85f4-544d4ea9fd6c.png)

System environment variables:

![image](https://user-images.githubusercontent.com/12248943/72201459-eb726600-345c-11ea-80f9-68e054cb230c.png)

From other issues I saw that you recommend doing some diagnostics, so here is the result of that: 

![image](https://user-images.githubusercontent.com/12248943/72201479-270d3000-345d-11ea-9d93-de61e6238d40.png)

Also I noticed that I do not have a log file after running the `install.py` script so I can not paste it here.

System info:
 - OS: Windows 10 Pro 1809 (build 17763.914)
 - Python Version: 3.8.1

Any help would be appreciated!

**Comment by iamkroot** [comment]
@nvvasilev Do you get this error on running this script again after installing poetry?

**Comment by nvvasilev** [comment]
@iamkroot Yes I do.

**Comment by iamkroot** [comment]
Also, have you restarted your terminal after installing poetry?

**Comment by nvvasilev** [comment]
Yes I restarted the terminal. 
Here is the output of `python -c "import subprocess as sp;sp.run(['poetry', '--version'])"`:

![image](https://user-images.githubusercontent.com/12248943/72201781-32ae2600-3460-11ea-9a30-4040841b8861.png)

**Comment by iamkroot** [comment]
Yup, that shouldn't be showing an error. What does `python -c "import os;print(os.environ['PATH'])" give?

**Comment by nvvasilev** [comment]
Here is the result of `python -c "import os;print(os.environ['PATH'])"`

![image](https://user-images.githubusercontent.com/12248943/72202250-c2a29e80-3465-11ea-9fb8-9cd6e01e4149.png)

**Comment by iamkroot** [comment]
The poetry folder doesn't show up here for some reason. Tried restarting your PC?

**Comment by nvvasilev** [comment]
Isn't it this one: `C:\Users\nikol\.poetry\bin C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\` ?
Row 4 of my prev comment of the output.

**Comment by nvvasilev** [comment]
I also tried restarting the machine a couple of times but with no success..

**Comment by iamkroot** [comment]
> Row 4 of my prev comment of the output.

You're right. I should've looked more carefully.

Can you open that folder and confirm that `poetry.exe` is present there? Also, try `python -c "import subprocess as sp;sp.run(['echo', '%PATH%'])"` and `python -c "import subprocess as sp;sp.run(['where', 'poetry'])"`

**Comment by nvvasilev** [comment]
Actually in `C:\Users\nikol\.poetry\bin` I only have these 2 files: `poetry` and `poetry.bat`

![image](https://user-images.githubusercontent.com/12248943/72215630-ed502e00-351d-11ea-825d-24a53804336d.png)

And here is the output of the commands:

![image](https://user-images.githubusercontent.com/12248943/72215634-03f68500-351e-11ea-9e3a-71337a99a168.png)

So maybe I have to get `poetry.exe` in the `C:\Users\nikol\.poetry\bin` folder somehow?

**Comment by iamkroot** [comment]
In the normal cmd, what does `where poetry` give?

**Comment by nvvasilev** [comment]
Here is the output:

![image](https://user-images.githubusercontent.com/12248943/72221059-ae42cc80-355f-11ea-8581-920915ef6ca7.png)

**Comment by iamkroot** [comment]
Hmm then I don't really see why the install script is failing :/ 

Let's try one thing. Run `python -c "import subprocess as sp;sp.run(['poetry', '--version'], shell=True)"` and let's see if it works.

**Comment by nvvasilev** [comment]
Ok, here is the output:

![image](https://user-images.githubusercontent.com/12248943/72223336-4f3c8200-3576-11ea-8c57-fa22021aa4d2.png)

I have four other versions of python installed (2.7, 2.7.15 (64-bit), 3.4.3 and 3.6.8). Can they somehow mess up the script?

**Comment by iamkroot** [comment]
Maybe, I guess the poetry installation might have some bug. But the fact
that the command worked means we have a solution for your issue.

Open up `install.py` file and in every place where you see a `sp.run(...`
line, just add `, shell=True` as an argument to the function, like so:
`sp.run(["poetry", "install", "--no-dev"])`becomes `sp.run(["poetry",
"install", "--no-dev"], shell=True)`. That should fix the problem.

**Comment by nvvasilev** [comment]
Ok, I will try it and report the result back.

**Comment by nvvasilev** [comment]
Output: 

![image](https://user-images.githubusercontent.com/12248943/72224353-51a4d900-3582-11ea-9319-cb936e351f37.png)

**Comment by nvvasilev** [comment]
You are right that adding `, shell=True` fixed the problem with requiring `poetry`. 
Should I open another issue for the file not found issue? :\

**Comment by iamkroot** [comment]
@nvvasilev it seems you missed modifying one line (line #69) where you need to put `, shell=True` too.

**Comment by deathishere420** [comment]
this is what i get after i did what you said to do 

Starting installation for trakt-scrobbler
Installing to C:\Users\adew7\AppData\Local\trakt-scrobbler
Installing dependencies from lock file

No dependencies to install or update

config.toml already exists in C:\Users\adew7\AppData\Roaming\trakt-scrobbler. Please ensure that it matches sample_config.toml, or the app may crash unexpectedly.
Validating config file at C:\Users\adew7\AppData\Roaming\trakt-scrobbler
Starting device authentication
Traceback (most recent call last):
  File "install.py", line 227, in <module>
    main()
  File "install.py", line 219, in main
    perform_trakt_auth(install_dir)
  File "install.py", line 201, in perform_trakt_auth
    sp.run(["poetry", "run", "python", "-c", trakt_cmd], cwd=str(install_dir))
  File "C:\Users\adew7\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\adew7\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\adew7\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by nvvasilev** [comment]
We are getting closer! 

![image](https://user-images.githubusercontent.com/12248943/72289457-d9a6e380-3653-11ea-9fd0-d2bd164fefc1.png)

Maybe I have to put `, shell=True` somewhere else as well?

**Comment by nvvasilev** [comment]
Got it! On line 99 `["poetry", "env", "info", "-p"], shell=True, cwd=str(install_dir), text=True` the `sp.check_output` function.

And now I just have to reboot.

![image](https://user-images.githubusercontent.com/12248943/72289793-841f0680-3654-11ea-9efb-4f5449dac799.png)

**Comment by nvvasilev** [comment]
How can I tell if it is working and is there an easy test I can make with a movie or an show episode? What should I see in trakt.tv? I am new to that site and it is a little confusing and overwhelming with information. 

And thanks for the help!

**Comment by iamkroot** [comment]
@nvvasilev Dont worry. You can look through the log file to see if the scrobbler has started correctly. (location is given in the README file)

**Comment by nvvasilev** [comment]
Here is the log after restarting the PC and after a few minutes starting VLC player manually:

`DEBUG - MainThread - utils - C:\Users\nikol\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
DEBUG - MainThread - utils - C:\Users\nikol\AppData\Roaming\trakt-scrobbler\trakt_token.json doesn't exist.
INFO - MainThread - trakt_interface - Access token not found in config. Initiating device authentication.
INFO - MainThread - trakt_interface - Verification URL: https://trakt.tv/activate
INFO - MainThread - trakt_interface - User Code: 0FC1F06B
DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
DEBUG - MainThread - trakt_interface - Waiting for user to authorize the app.
INFO - MainThread - trakt_interface - Device auth successful.
DEBUG - MainThread - utils - C:\Users\nikol\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
DEBUG - MainThread - utils - C:\Users\nikol\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
INFO - MainThread - scrobbler - Started scrobbler thread.
DEBUG - MainThread - utils - C:\Users\nikol\AppData\Roaming\trakt-scrobbler\watched_cache.json doesn't exist.
INFO - MainThread - monitor - Started monitor for vlc
INFO - vlc - monitor - Unable to connect to vlc. Ensure that the web interface is running.
DEBUG - MainThread - utils - C:\Users\nikol\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
DEBUG - MainThread - utils - C:\Users\nikol\AppData\Roaming\trakt-scrobbler\trakt_cache.json doesn't exist.
INFO - MainThread - scrobbler - Started scrobbler thread.
INFO - MainThread - monitor - Started monitor for vlc
INFO - vlc - monitor - Unable to connect to vlc. Ensure that the web interface is running.
`
I noticed that the web interface is running only when VLC player is launched. Does that mean that when I start it the vlc monitor will connect and start monitoring it. I don't get a log update after I start VLC player and the web interface is available, saying that the monitor is connected.

**Comment by iamkroot** [comment]
Are you sure your interface is working, and that the port/password have been specified properly in the config file?

**Comment by iamkroot** [comment]
Closed, since the main issue has been fixed. If you are still facing problems with scrobbling, please create a new issue.
