### ISSUE TITLE
[Question] about monitor connecting to a player

### ISSUE THREAD

**Issue by nvvasilev** [iamkroot/trakt-scrobbler#45]
Hello again @iamkroot,

After the previous issue #44 I got to the point where I get this in the log file:

![image](https://user-images.githubusercontent.com/12248943/72373914-e68a0c80-3711-11ea-9334-0f9a4d77a850.png)

As I understand the vlc player monitor has started successfully. 
However it does not connect to the VLC web interface. 

I double checked whether the port and the password are set correctly everywhere and they are.
The web interface is working BUT it is only working when the VLC player is running. 

I guess my question is whether when I start VLC player to watch something is the monitor going to connect to the player and scrobble what I watched?

**Comment by prabapro** [comment]
Hi @nvvasilev ,

I also faced the similar issue & managed to get it worked. But I'm on a Mac, so not sure whether the steps I followed would help you. However, here's what I did;

1. Reset the VLC settings to default
2. Interface > Main Interface > Lua > Lua Interface - enter `dummy`
![image](https://user-images.githubusercontent.com/32594937/72407847-e6782400-3786-11ea-971b-1c36de33e25c.png)

3. My previous password was just numbers. So this time I set up a strong one
4. Go to Input/Codecs > Scroll down to Network settings > Set `8080` as HTTP Server Port 
![image](https://user-images.githubusercontent.com/32594937/72407870-fa238a80-3786-11ea-97cc-15d0c97768b2.png)
5. Restat the VLC & tried `http://localhost:8080`
6. Update `config.toml` with the new password & the port
7. After a reboot, scrobble started successfully.

**Comment by nvvasilev** [comment]
Hi @prabapro,

My VLC player configuration is the same as yours and I can access the web interface on `http://localhost:8080`, but only when the VLC player application is running. 

I will try to reset VLC's config to the defaults and reconfigure the password and port and see if it helps.

**Comment by prabapro** [comment]
> Hi @prabapro,
> 
> My VLC player configuration is the same as yours and I can access the web interface on `http://localhost:8080`, but only when the VLC player application is running.
> 
> I will try to reset VLC's config to the defaults and reconfigure the password and port and see if it helps.

Hey @nvvasilev , for me also it's same. localhost:8080 is accessible only when the VLC application is in use. I guess this make sense as the scrobbler should run when we play something on the VLC app. Probably @iamkroot would be able to comment on this. Cheers.

**Comment by iamkroot** [comment]
Hey @nvvasilev 
Basically,
* This app is designed to start with your PC and has a "monitor" for each media player you specify. 
* This monitor keeps checking if the media player is running or not. If not, you get the "Could not connect..." message.
* If the player is running, then the monitor extracts the currently playing media information from the player, processes it, and sends that to trakt.
* When the player is closed, the monitor goes back to "dormant" state, where it waits for the player to start again.
* The checking happens at a set interval (`poll_interval` in config, 10 secs by default), which is the _maximum_ delay between you starting the player, and the monitor recognizing that activity. So while testing, you should keep your player open for at least this much period.

I guess I should add a "How it Works" section in the README.

**Comment by nvvasilev** [comment]
Thanks for the explaination @iamkroot,

I will test this tonight. 
Should there be a log in the log file when the monitor successfully connects to the media player or not?

**Comment by iamkroot** [comment]
@nvvasilev Not really, but you will get logs when you play some media.

**Comment by nvvasilev** [comment]
@iamkroot Ah, ok! Will test with some media playback.

**Comment by nvvasilev** [comment]
@iamkroot Thanks for the help.

It work as you described it! Once I play something with the VLC player I get a notification that the scrobller started successfully and there is also a log entry:

![image](https://user-images.githubusercontent.com/12248943/72560867-95fce580-38b0-11ea-8a5a-573b6b52d28f.png)

Thanks for the help. I think you can close this issue as well.
Have a good one!

**Comment by nvvasilev** [comment]
Also just to note that the sync work and I received an update on a trakt.tv Android app client so I can say that I am happy with the library and thanks again @iamkroot :)

**Comment by iamkroot** [comment]
Awesome
