### ISSUE TITLE
Install script fails

### ISSUE THREAD

**Issue by utkarshsethi** [iamkroot/trakt-scrobbler#47]
**Describe the bug**
Install script fails

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.8.1
 - Player VLC
 - Player Version 3.0.8

**To Reproduce**

	python install.py

<details><summary>CMD Op</summary>
C:\Users\utkar\Documents\trakt-scrobbler-master\tools>python install.py
Starting installation for trakt-scrobbler
Installing to C:\Users\utkar\AppData\Local\trakt-scrobbler
'poetry' is not recognized as an internal or external command,
operable program or batch file.
config.toml already exists in C:\Users\utkar\AppData\Roaming\trakt-scrobbler. Please ensure that it matches sample_config.toml, or the app may crash unexpectedly.
Validating config file at C:\Users\utkar\AppData\Roaming\trakt-scrobbler
'poetry' is not recognized as an internal or external command,
operable program or batch file.
Invalid config file!
<p>
</p>
</details>

**Log file**
<details><summary>None Generated</summary>
<p>
None Generated
</p>
</details>

**Comment by utkarshsethi** [comment]
`[general]
enable_notifs = true

[fileinfo]
whitelist = []

# example regexes (uncomment to activate). To test your custom regexes, try regex101.com
[fileinfo.include_regexes]  # custom regex to identify media information, should be posix path. Use single quotes for the strings.
movie = [
	# '.*/(?P<name>.+?) \((?P<year>[0-9]{4})\).*',  # matches /a/b/Taxi Driver (1976).mkv
]
episode = [
	# '.*/(?P<title>.+?) \[[0-9]{3,4}p\]/(?P<episode>\d+) - (?P<episode_title>.*)\.[a-z]{3,4}',  # matches "/a/b/One Punch Man [1080p]/01 - Return of the Hero.mkv"
	# '.*/(?P<title>.+?)\s*?(\[[0-9]{3,4}p\])?/(S|Season)\s?(?P<season>\d+)/(?P<episode>\d+).*',  # matches "/a/b/Mob Psycho 100/Season 2/01 - Ripped Apart ~Someone Is Watching~.mkv"
]

[players]
monitored = ['vlc']  # players to be monitored. Allowed: 'mpcbe', 'mpchc', 'mpv', 'plex', 'vlc'
skip_interval = 5  # min percent jump to consider for scrobbling to trakt

[players.mpcbe]  # enable web interface from options
ip = "localhost"
port = "13579"  # from Options -> Player -> Web Interface -> Listen on port  (ensure it is ticked) 
poll_interval = 10  # in seconds. How frequently the monitor should check for player update.

[players.mpchc]  # enable web interface from options
ip = "localhost"
port = "13579"  # if both mpchc and mpcbe are to be monitored, then ensure that their ports are different
poll_interval = 10  # in seconds

[players.vlc]  # enable web interface from options
ip = "localhost"
port = "8080"  # from Preferences -> All -> Input/Codecs -> HTTP Server Port
password = "password"  # from Preferences -> All -> Interface -> Main Interfaces -> Lua -> Lua HTTP Password
poll_interval = 10  # in seconds. How frequently the monitor should check for player update.

[players.mpv]  # enable the JSON IPC server. Either via cmd line arg (eg: --input-ipc-server=\\.\pipe\mpvpipe), or in mpv.conf file
ipc_path = '\\.\pipe\mpvpipe'  # windows (single quotes are important)
# ipc_path = "/tmp/mpvsocket"  # unix

[players.plex]
ip = "localhost"  # IP of the plex server. Only supports http for now.
port = 32400
login = "login"
password = "password"
poll_interval = 10  # in seconds. How frequently the monitor should check for player update.
`

**Comment by utkarshsethi** [comment]
>python --version
Python 3.8.1

**Comment by iamkroot** [comment]
You'll have to install [poetry](https://python-poetry.org/docs/) first, and then run the script.

**Comment by iamkroot** [comment]
@utkarshsethi I've clarified the instructions in the README.

**Comment by utkarshsethi** [comment]
I feel so embarrassed now.... Thanks for quick reply.
