### ISSUE TITLE
Need to manually run the script on each playback

### ISSUE THREAD

**Issue by rohitghali** [iamkroot/trakt-scrobbler#5]
Every time I start playback in some player, it scrobbles only after running the command "pipenv run python main.py". It is not scrobbling manually. Windows 10 x64. And movies are not being marked as watched after completion of playback. Am I doing something wrong? Please help.

**Comment by rohitghali** [comment]
A simple restart fixed the auto scrobble problem. I also disabled the mpchc as both mpchc and mpcbe were listening to the same port. Thanks for the script.

Not able to get it working with mpv though. I think it is a problem with input-ipc-server. This is what I typed into the mpv config file "input-ipc-server=\\\\.\\pipe\\mpvpipe" Am I doing anything wrong? Please help.

**Comment by iamkroot** [comment]
Seems like this is a pretty common issue being faced, I'll make sure to update the README. Thanks for creating the issue, and sorry I couldn't reply earlier :)
