### ISSUE TITLE
[BUG] Not scrobbling VLC playing GVFS urls

### ISSUE THREAD

**Issue by marek-saji** [iamkroot/trakt-scrobbler#53]
**Describe the bug**

Remote files mounted in Nautils (GNOME’s “Files“) are not scrobbled.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python 3.7.5
 - Player vlc
 - Player Version 3.0.8-0-gf350b6b5a7

**To Reproduce**
1. Mount samba / sftp URL
2. Open any file

**Log file**
```
WARNING - vlc - utils - Invalid file uri 'sftp://HOST/PATH/Urlencoded%20file%20name.mkv'
```

**Comment by iamkroot** [comment]
I'd assumed all files were on the system itself 😅

I'll have to make some changes, but it should be possible to add support for this.

**Comment by iamkroot** [comment]
@marek-saji Please update to v1.0.0b1 and give it a try!

**Comment by marek-saji** [comment]
Fixed :tada:

Thank you for the whole scrobbler, great work. :smiley:
