### ISSUE TITLE
getting a [ConfigTypeError] 

### ISSUE THREAD

**Issue by emielregis-008** [iamkroot/trakt-scrobbler#57]
I removed the old scrobbler version according to instructions, installed the new one. I can't get to configuring it however:

```
PS` C:\> trakts init
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

[ConfigTypeError]
fileinfo must be a collection, not NoneType
```

**Comment by emielregis-008** [comment]
Sorry, there was one directory left over from the old version in AppData/roaming, after deleting it trakts init works.

**Comment by iamkroot** [comment]
Hmm, that should not have happened. The files in Roaming are just data files, and shouldn't cause an error on running the new version.

Did you run `trakts config` before `init`?

**Comment by emielregis-008** [comment]
No, I did not run `trakts config` before `trakts init`. The install instruction don't mention it.

**Comment by iamkroot** [comment]
Do you still have the contents of your previous roaming/trakt-scrobbler folder? It'd be a great help to see what files were present to pinpoint the bug

**Comment by emielregis-008** [comment]
[trakt-scrobbler_roaming_old.zip](https://github.com/iamkroot/trakt-scrobbler/files/4483783/trakt-scrobbler_roaming_old.zip)

Here you go. After I deleted this folder `trakts init` worked.

**Comment by iamkroot** [comment]
Are you sure you had the `config.yaml` file there before running even a single `trakts ...` command? That file should only be made _after_ `trakts init` is run.

**Comment by emielregis-008** [comment]
> 
> 
> Are you sure you had the `config.yaml` file there before running even a single `trakts ...` command? That file should only be made _after_ `trakts init` is run.

This folder seemed to me a remnant from the old pre command line version. I just didn't think of removing it.
