### ISSUE TITLE
[REQUEST] SOCKS5

### ISSUE THREAD

**Issue by 2803media** [iamkroot/trakt-scrobbler#60]
Hi thanks for this amazing software!

Do you know if it will be possible to add option to connect a SOCKS5 proxy?

https://stackoverflow.com/questions/12601316/how-to-make-python-requests-work-via-socks-proxy

Thanks for your feedback this feature could bring a bit of anonymous!

**Comment by 2803media** [comment]
Maybe something like that :

```
session = requests.session()
session.proxies = {}
session.proxies['http'] = 'socks5h://user:pass@proxy-nl.privateinternetaccess.com:1080'
session.proxies['https'] = 'socks5h://user:pass@proxy-nl.privateinternetaccess.com:1080'

```

The question is now where to put this code...

For the record it's need:

`sudo python3 -m pip install pysocks`

**Comment by iamkroot** [comment]
Hey @2803media, I've added support for proxies. Check the configuration section in readme to know how to set it. Give it a try!

**Comment by 2803media** [comment]
thanks @iamkroot I will test this release ASAP

Best!

**Comment by 2803media** [comment]
I try but can't find a way to make it work, i test with my paid socks5 and with some of this list too http://spys.one/en/socks-proxy-list/

Best

**Comment by iamkroot** [comment]
Are you sure you installed it properly? See the installation instructions, you need to add the extra dependency

**Comment by 2803media** [comment]
damned I miss the dependency part ;) I will test that after lunch

**Comment by 2803media** [comment]
I try to reinstall from scratch as the upgrade doesn't seem to work with the extra  but it fails
```
pipx install trakt-scrobbler --extras socks
usage: pipx [-h] [--version] {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall-all,list,run,runpip,ensurepath,completions} ...
pipx: error: unrecognized arguments: --extras socks
```

**Comment by iamkroot** [comment]
Aah, sorry about that! I put the wrong install command there. Try `pipx install trakt-scrobbler[socks]`

**Comment by 2803media** [comment]
no problem ;) 
here are my tests:

```
pipx install trakt-scrobbler[socks]
zsh: no matches found: trakt-scrobbler[socks]
```

```
pipx install trakt-scrobbler [socks]
zsh: no matches found: [socks]
```

**Comment by iamkroot** [comment]
ah you're using zsh. You'll need to escape the square brackets (`\[`, `\]`) or do `"trakt-scrobbler[socks]"`

**Comment by 2803media** [comment]
Perfect it's working !
I just need to verify that it use the sock5 but scrobbler send info to trakt.tv
Thanks again
