### ISSUE TITLE
[BUG] vlc - monitor - Unable to connect to vlc. Ensure that the web interface is running. (After every episode)

### ISSUE THREAD

**Issue by wadforth** [iamkroot/trakt-scrobbler#70]
**Describe the bug**
After I watch any episode on VLC, I close VLC and open another episode. Upon opening the next episode, it doesn't begin to scrobble, so checking the log file it says its unable to connect to VLC. So I have to keep disabling/enabling web interface, removing and readding password and restarting the monitors to get it to work again.

This happens every time, unsure why and it's not really realistic to try and fix it everytime I want to watch another episode. Nothing looks out the ordinary in the log file.

**Example**
Open Episode 1 in VLC - works fine, starts to scrobble!
Close VLC after Episode 1 has finished.
Open Episode 2 in VLC - doesn't start to scrobble, says unable to connect to VLC.

**Desktop (please complete the following information):**

OS: Windows 10
Python Version: 3.8.2
Player VLC
Player Version 3.0.10

**To Reproduce
Steps to reproduce the behavior:**

Open Episode, finish, close VLC
Open next episode

Any help would be appreciated.
[trakt_scrobbler.log](https://github.com/iamkroot/trakt-scrobbler/files/4724958/trakt_scrobbler.log)

**Comment by wadforth** [comment]
I'd like to add, addition to the previously log, I tried to watch another episode - it started scrobbling, but hasn't ended the scrobbling even though the episode has ended and VLC has closed. Seems to be just hanging.

[trakt_scrobbler.log](https://github.com/iamkroot/trakt-scrobbler/files/4725465/trakt_scrobbler.log)

**Comment by iamkroot** [comment]
@wadforth I'd recommend reading through [How It works](https://github.com/iamkroot/trakt-scrobbler#how-it-works) section to understand what is happening behind the scenes, specifically, the [polling](https://github.com/iamkroot/trakt-scrobbler#polling-for-activity) part. Basically, there will be a maximum of 10 second delay between any action on the player and the corresponding scrobble. 

The second thing *might* be a bug, but I haven't been able to reproduce it reliably to understand what causes it.

**Comment by wadforth** [comment]
Did a fresh install of python, pip and the scrobbler. Will re-open if persists.
