### ISSUE TITLE
Uninstallation procedure wrong?

### ISSUE THREAD

**Issue by Hillgrove** [iamkroot/trakt-scrobbler#75]
First of all.. THANKS for an amazing app/script/whatever. It's been a real help.

I been using an old version of this code for a long time and just saw there has been updates for it.

So I'm trying to uninstall it, but I can't complete this step:

poetry env remove python3 (to remove python environment.)

With some digging it seems poetry is a package manager for python, used to ease installation of scripts etc. I never installed trakt-scrobbler via poetry.

I'm guessing I can just delete the folder and that's it, but I'd love your input on it, as Python is something I never really used.

**Comment by iamkroot** [comment]
>  I never installed trakt-scrobbler via poetry.

Wow! :sweat_smile: I'm happy to see that the app is working fine even after so long :)

> I'm guessing I can just delete the folder

I'm afraid it won't be so simple. While it will technically stop working, there will still be some artifacts remaining that ought to be removed. Specifically, before `poetry`, I used `pipenv` for the same purpose (dependency management). So I'm assuming that will be installed for you. The equivalent command will be simply `pipenv --rm` (ensure you are inside the correct directory). Further, you'll also want to remove pipenv itself if you aren't using it. `pip uninstall pipenv` should do the trick if you used the install script originally.

Thanks for the issue! I ought to update the README.

**Comment by Hillgrove** [comment]
Thanks for the quick reply :)

I'm getting this error when running `pipenv --rm` inside the `%LOCALAPPDATA%\trakt-scrobbler` folder.


```
Removing virtualenv (C:\Users\Hillgrove\.virtualenvs\trakt-scrobbler-rkOWzqHK)…
[  ==] Running...Error:  An error occurred while removing C:\Users\Hillgrove\.virtualenvs\trakt-scrobbler-rkOWzqHK!
[WinError 145] The directory is not empty: 'C:\\Users\\Hillgrove\\.virtualenvs\\trakt-scrobbler-rkOWzqHK\\Lib\\site-packages\\pywin32_system32'

```

**Comment by Hillgrove** [comment]
update: disregard the last message.

For some reason I still had an instance of the script running, and I killed it in taskmanager. Code ran fine afterwards.

**Comment by Hillgrove** [comment]
and a follow up.

Installing pipx seems to work fine, but when installing trakt-scrobbler I encountered an error. Turns out I needed to add `%USERPROFILE%\AppData\Roaming\Python\Python37\Scripts` to my `PATH` Environment Variables.
