### ISSUE TITLE
[BUG] Trakts stops when powershell is closed

### ISSUE THREAD

**Issue by cdmichaelb** [iamkroot/trakt-scrobbler#78]
**Describe the bug**
Trakts works and runs fine as long as power shell is open. As soon as it is closed, it stops.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.8
 - Player: MPC-BE
 - Player Version: 1.5.5

**To Reproduce**
1. 'trakts start' in power shell
2. Close power shell
3. Open new power shell
4. 'trakts status'

**Log file**
<details><summary>Click to see log contents</summary> 
<p>

```
Command: "trakts log open" just opens command prompt at C:\. Attempting to run the command in command prompt just opens a new one. No log is given.
```
</p>
</details>

**Comment by iamkroot** [comment]
Maybe have a look at #63?

**Comment by cdmichaelb** [comment]
It seems like it's on the right track. Sadly it didn't work for me, not even the unrecommended method. Editing the executable gives me this error.

> Program 'trakts.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1
char:1
+ trakts
+ ~~~~~~.
At line:1 char:1
+ trakts
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by iamkroot** [comment]
Just to clarify, renaming `python.exe` to `pythonw.exe` makes it run in the background, but it breaks the normal command output?

**Comment by cdmichaelb** [comment]
Clarifying a bit, I didn't rename the actual python executables, I hexedit-ed the trakts.exe file to change python.exe to pythonw.exe. I assume that renaming the python executables may have the same effect though I didn't test that.

But otherwise yes, it runs in the background but breaks normal command output.

**Comment by cdmichaelb** [comment]
I found this explanation here as to what's going on and why this hack works
for us. https://stackoverflow.com/a/30313091

Perhaps could somehow implement it so trakts start uses pythonw while
everything else uses python?

**Comment by iamkroot** [comment]
What I'm more confused about is why this issue is showing up only on some systems. The current installation works completely fine on my Windows setup. I suspect this is an upstream bug with [`pipx`](https://pipxproject.github.io/pipx/), the tool we're using to install the package. More experimentation is required.

**Comment by iamkroot** [comment]
Rejoice my friends! Thanks to @JourneyOver, I was finally able to pin down the bug to the way [`START /b`](https://ss64.com/nt/start.html) works in Windows. 

The reason we need `START /b` is that it is the simplest way to run a console app without actually creating a new window. Basically, it creates a separate process in the background, _but_ it gets killed along with the parent. To handle this, we need to have a parent process that _also_ runs in the background without a window, and that's where `pythonw.exe` comes in.

So when we run `trakts start`, the following happens,
1. Fork a new process to `pythonw.exe`, which is a truly separate process, running in the background.
2. `pythonw.exe` then forks to `start /b trakts run` which creates the actual `trakts` background process.

To be fair, the second step isn't strictly necessary. We could just point `pythonw` to `main.py` and it will work as expected. But this will break the process commands like `trakts stop` and `trakts start -r`, which need `trakts run` specifically. I'm leaving this as a TODO for now.

**Comment by iamkroot** [comment]
Paging @cyatek and @Umair444 too in case you wanna update.

**Comment by iamkroot** [comment]
To try out the fix, do:
1. `trakts stop`
2. `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git`
3. `trakts start`

**Comment by JourneyOver** [comment]
Can confirm that it works @iamkroot ^^ ran through the update process and then went and did a `trakts start` and it stayed running after I had closed out of my command prompt

**Comment by bonswouar** [comment]
@iamkroot First, thank you for you investigation !

Although I did force install the latest version as you recommended, but still having the problem, no background process when cmd is closed.

What I don't understand though is why was it was working (for me) before ? Did something change in the way it starts ? That Windows background problem wasn't always here ?!
I did uninstall python at some point though and had to reinstall everything, it might be linked. And I had a `trakt-scrobbler.bat` script on statup that doesn't seem to work anymore. I might just try to reinstall it all again ;)

**Comment by JourneyOver** [comment]
@bonswouar you might of ran into the same issue I did at first which was that even though you force installed through `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git` it didn't actually install the version from git..

I would suggest either downgrading to an earlier version or uninstalling your current version of trakt scrobbler and then re-installing it with `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git`.

**Comment by bonswouar** [comment]
Thanks @JourneyOver that worked !

_Although I now have an error from the API "The origin web server timed out responding to this request", but it's probably just a temporary issue with their server._

**Comment by ipdisifil** [comment]
I have the same problem. trakts.exe removes itself from task manager as soon as I close the cmd tab. I tried:

> 
> 
> @bonswouar you might of ran into the same issue I did at first which was that even though you force installed through `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git` it didn't actually install the version from git..
> 
> I would suggest either downgrading to an earlier version or uninstalling your current version of trakt scrobbler and then re-installing it with `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git`.

this but still didn't solve the problem. I also tried: 

>
> 
> If Still Not Work Try (NOT-RECOMMENDED):
> 
>     1. C:\Users<UserName>.local\bin
> 
>     2. Open `trakts.exe` in notepad
> 
>     3. Search for python.exe, and change it to pythonw.exe, there should be a single python.exe in here.
> 
>     4. Start scrobbler --> Close CMD --> Open Task Manager (CTRL+SHIFT+ESC) --> Details --> Search for trakts.exe, it should be running. Also, search python.exe. If with these steps worked for you, then there'll be pythonw.exe process instead of python.exe.

this but didn't help either.

**Comment by ipdisifil** [comment]
@bonswouar `trakts.exe` is not removed. I re-installed it and tried the second solution again and it's working now. I can use cmd commands but can't see the respond messages. In task manager, ` trakts.exe` and `pythonw.exe` seems like working all time, I don't know if that's a bad thing.
