### ISSUE TITLE
[Request] user filter

### ISSUE THREAD

**Issue by JourneyOver** [iamkroot/trakt-scrobbler#80]
Would like to see a user filter so that random plays from other users who are watching stuff on my server doesn't get scrobbled to trakt and only plays that I myself do get scrobbled.

**Comment by JourneyOver** [comment]
any word on how this is possibly going @iamkroot ?

**Comment by iamkroot** [comment]
Hey @JourneyOver, implementing this is gonna require substantial change in the codebase, since the current plex monitor is pretty dumb. I'll try to hack on it over the weekend.

**Comment by JourneyOver** [comment]
@iamkroot Kinda figured it probably would, but sounds good. It'd just be nice to have as I've been having a lot of issues lately with the plex trakt.tv plugin not scrobbling sometimes or random other BS, so I ended up looking for an alternative and found this and so far have liked it, but the only thing I don't like is the whole scrobbling for all users as sometimes my friend ends up watching something on his account and it would get scrobbled to my trakt.tv account.

**Comment by iamkroot** [comment]
Hey @JourneyOver, update to the newest version, and set the `scrobble_user` field in the config.

Run: `trakts config set players.plex.scrobble_user <USERNAME>` (replace `<USERNAME>` with whatever Plex shows as name of the user in the UI)

**Comment by JourneyOver** [comment]
Great! Thanks a bunch :D will def test it out when I get a chance and report back if everything is working.

**Comment by JourneyOver** [comment]
So far things look to be working great 👍

**Comment by JourneyOver** [comment]
@iamkroot okay I guess I was wrong on it working great, it seems to be a bit glitchy, as I decided to look at the logs today after it decided it didn't want to scrobble a video I played.

Looking at the logs, it seems that sometimes there isn't a `Scrobble start successful` in the logs for a video and it'll only log either the `pause` (or the `stop`) and then the `scrobble start` after a `pause`.

and just now I played `The Boys S02E07` and nothing appeared in the logs at all for said video and it didn't get scrobbled to trakt, the last video it had scrobbled for was `The Boys S02E06` which I watched yesterday night.

[trakt_scrobbler.log](https://github.com/iamkroot/trakt-scrobbler/files/5322395/trakt_scrobbler.log)


so I'm not sure if it's just the user filter being kinda iffy right now or what could possibly be happening.

**Comment by iamkroot** [comment]
@JourneyOver that's weird. Did you play Ep6 and ep7 from the same userid and the same plex client? Maybe plex has different usernames in different clients.

**Comment by iamkroot** [comment]
I've pushed some code which will add extra debugging logs to the plex monitor. Try installing it via `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git@plex-fix` and then `trakts start -r` to restart. Attach the log file(s) once you find some anomaly.

**Comment by JourneyOver** [comment]
> @JourneyOver that's weird. Did you play Ep6 and ep7 from the same userid and the same plex client? Maybe plex has different usernames in different clients.

@iamkroot Yes I played it from the same userID and same plex client, and had no changes between when I played Ep6 and Ep7. 

I will try with the extra debugging logs build later today after I get off work and should hopefully have some logs for you between tonight and possible tomorrow.

**Comment by JourneyOver** [comment]
ofc during testing I can't get it to glitch out like it was before >.< Maybe it's because I restarted my computer between during the time that it was glitching out and the now testing. I'll continue testing things out and see if I run into any issues or not over the next several days or so.

**Comment by JourneyOver** [comment]
@iamkroot so I think I found out the reason on why it didn't scrobble/see `The Boys S02E07` and possibly some of the glitches I was experiencing. it seems to mostly be because when I updated to the latest release I went through the update process and restarted trakts in cmd and I ended up running into the #78 issue as I had closed out of my command prompt that I had restarted trakts with at some point before I watched `S02E07`.

Can't say if it was a cause of any of the random little glitches I was running into as well but thinking about it, it is a possibility. As I haven't had any issues at all while keeping my command prompt open after doing a trakts start (or if I restart my computer and don't mess with any trakts stop/start at all)

**Comment by iamkroot** [comment]
Oh boy, that's a tough one. I haven't been able to reproduce #78 on my machine, but I'll try to see if the update process is the culprit. The Windows background runner is extremely fragile, since it directly interacts with the python process instead of using the Window service functionality (which is also broken in many ways). I'll try to find time over the weekend to get to the root of #78.

**Comment by JourneyOver** [comment]
@iamkroot See the thing is, is that if I restart my computer or log out and back in (or if I just go and run the .vbs script from the autostart command) it runs just fine with and without cmd open so I'm not running into that part of #78 .. main part seems to be if I was to go into cmd and say do a `trakts stop` for whatever reason and then eventually a `trakts start` or `trakts start -r` and then close cmd it closes out of trakts as well.

It seems like the operation of trakts is hooked to the command prompt / powershell when the `trakts start` is activated through command prompt / powershell, while having it run through the .vbs script either at computer startup or manually going and running it makes it hooked to an invisible shell.

anyways if you need help testing or anything, I will gladly help out in anyway I can.

Edit before I actually post this: I ended up testing something because I noticed that trakts is always connected to `python.exe`, I went into the `.local\pipx\venvs\trakt-scrobbler\Scripts` folder and renamed `python.exe` to `python.exe.bak` and renamed the `pythonw.exe` to `python.exe` and did a `trakts start` and it sort of ran in a way (it started up but it just threw errors in the `.log` file but it kept running), but closing the command prompt did not seem to shut down trakts at all.

I didn't test playing a video yet since it just threw errors in the logs but maybe if we could get trakts to run through pythonw (and without throwing errors) maybe then we could fix #78
