### ISSUE TITLE
[BUG] Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by Joosh-Booth** [iamkroot/trakt-scrobbler#81]
**Describe the bug**
After running trakst init and choosing VLC I am unable to find the directory even though the path is correct. If I choose no and either enable the auto start service, or say no and then yes to start scrobbler service now I get an error.

`Failed to connect to bus: No such file or directory

[CalledProcessError]
Command '['systemctl', '--user', 'start', 'trakt-scrobbler']' returned non-zero exit status 1.`

**Desktop (please complete the following information):**
 - OS: Ubuntu (WSL)
 - Python Version: 3.8.2
 - Player: VLC
 - Player Version: 3.0.11

**To Reproduce**
1. Run trakts init on the command line
2. Select either Enable autostart service for scrobbler, or Start scrobbler service now
3. Receive error

**Log file**
<details><summary>Click to see log contents</summary> 
<p>

```
Trakts uninitialised so no log file created
```
</p>
</details>

**Comment by iamkroot** [comment]
Hey @Joosh-Booth, if you're running Windows, just follow the normal installation steps, _outside_ of WSL. Running the scrobbler via WSL is simply not feasible due to lots of reasons and it just won't work.

**Comment by Joosh-Booth** [comment]
Yeah my mistake I'm dumb 🤷
