### ISSUE TITLE
Unable to set general.enable_notifs = False

### ISSUE THREAD

**Issue by psirek** [iamkroot/trakt-scrobbler#89]
Every time I try to set general.enable_notifs = False it sets it to True:

> trakts config set general.enable_notifs false
> User config updated with 'general.enable_notifs = True'
> Don't forget to restart the service for the changes to take effect.

It does not matter what value I give, it always sets it to "True"

**Comment by iamkroot** [comment]
Thanks for the bug report! This is happening because Python considers any non-empty string to be *truth-y*, so `bool("False") is True`. To make this work for now, just provide it an empty string: `trakts config set general.enable_notifs ""`.

I'll add some logic to handle the bool special case.

**Comment by psirek** [comment]
So simple! Thank you for the quick response, it was drivning me crazy :)
