### ISSUE TITLE
[BUG] Everything from the project just quits silently

### ISSUE THREAD

**Issue by markododa** [iamkroot/trakt-scrobbler#90]
Installed version from aur as well as modules from the git repo fail silently, importing modules works just fine, however help() and everything fails.

 doda  ~  trakts auth
 doda  ~  trakts ttjtfuftyfy
 doda  ~  trakts --help
 doda  ~  cd Repos/trakt-scrobbler/
/home/doda/Repos/trakt-scrobbler
 doda  ~  Repos  trakt-scrobbler  python
Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trakt_scrobbler
>>> help(trakt_scrobbler)
>>> trakt_scrobbler.gjffhggfgfhfh
>>> trakt_scrobbler.gjffhggfgfhfh()
>>>

**Comment by markododa** [comment]
(Pdb) n
> /usr/bin/trakts(33)<module>()
-> sys.exit(load_entry_point('trakt-scrobbler==1.1.2', 'console_scripts', 'trakts')())
(Pdb) n
AttributeError: module 'confuse' has no attribute 'yaml_util'

found it

**Comment by markododa** [comment]
Bumped my confuse version, everything works now!

**Comment by iamkroot** [comment]
The [`python-confuse`](https://aur.archlinux.org/pkgbase/python-confuse/) package on AUR is stuck on v1.1.0. I've flagged it as Out of date.

**Comment by iamkroot** [comment]
Maybe @ahmubashshir can update the minimum required version of `confuse` to `v1.3.0` in the `trakt-scrobbler` package.

**Comment by ahmubashshir** [comment]
I'm on my way home... after reaching home, I'll update it.

**Comment by ahmubashshir** [comment]
The PKGBUILD generates deps list from pypi... So if we update pyproject.toml, then deps will be updated automatically.
