### ISSUE TITLE
[BUG] Not scrobbling from Plex Media Server

### ISSUE THREAD

**Issue by Hillgrove** [iamkroot/trakt-scrobbler#98]
deleted as password was shown in plaintext

**Comment by Hillgrove** [comment]
I can add that it scrobbles fine from VLC.

**Comment by iamkroot** [comment]
Could you please run `trakts plex --force` to clear the existing token and try getting a fresh one?

**Comment by Hillgrove** [comment]
it failed the first time (I'm an idiot and didn't get the error message, but something about wrong credentials).

Ran it again and got this:

[FileNotFoundError]
[WinError 2] The system cannot find the file specified: 'C:\\Users\\Hillgrove\\AppData\\Roaming\\trakt-scrobbler\\plex_token.json'

**Comment by iamkroot** [comment]
> it failed the first time (I'm an idiot and didn't get the error message, but something about wrong credentials).

Then maybe you need to check the creds on your end?


> [FileNotFoundError]

Ah this is a slight bug in the command. Run it with `trakts plex`, without the `--force` part. `--force` assumes the file is always present, but that won't be true if you just deleted it :P

**Comment by Hillgrove** [comment]
thanks for the help.. worked if I typed instead of copy-pasting.

any way to delete my initial post? had no idea the log would contain pw's in plaintext.

**Comment by iamkroot** [comment]
> thanks for the help.. worked if I typed instead of copy-pasting.

awesome.


> any way to delete my initial post? had no idea the log would contain pw's in plaintext.

I can delete this entire issue altogether, but considering that the original post is already 2 days old, the github scrapers would have most likely picked it up. You should regard the password as compromised and take steps accordingly.

**Comment by Hillgrove** [comment]
it's been changed :)

but it also contains other personal information that I'd rather not have floating around for the average user :)

**Comment by iamkroot** [comment]
sure alright :) I'm adding a warning to the bug report template regarding this stuff.
